vitejs/docs-ja

- .vitepress/config.js
resolves #3
Cherry picked from https://github.com/vitejs/vite/commit/33ce885ab679cfd47fc29c0d88e5910b227370d6
> docs: link to ja translation (#3)

- guide/api-javascript.md
> 旧194 chore(docs): add colons to api pages #22

- config/index.md
- guide/build.md
> 旧192 feat: enable usage of function as library fileName, close #3585 #21

- guide/index.md
> 旧191 chore: update create-vite commands #20

- config/index.md
> 旧180 feat: allow passing options to rollupjs dynamic import vars plugin (#… #9

- config/index.md
> 旧179 docs: clarify CommonJS with optimizeDeps.exclude #8

- config/index.md
> 旧182 docs: add note about opening in a specific browser #11

- config/index.md
先程の PR でサジェストしたコードが textlint 違反していたので修正
> fix textlint

- config/index.md
> 旧183 docs: typos in config page #12

- config/index.md
> 旧184 docs: how to disable publicDir #13

- guide/api-plugin.md
> 旧185 docs: config hook is async #14

- guide/features.md
> 旧187 chore(docs): WebAssembly (no space) #16

- config/index.md
> refactor: deprecate polyfillDynamicImport #37

- config/index.md
- guide/api-plugin.md
- guide/build.md
- guide/features.md
- guide/migration.md
- guide/using-plugins.md
close #34 
close #59
typo があったので本体に PR
vitejs/vite#4445
> docs: exhibit defineConfig #34,#59

- README.md
> update link to CONTRIBUTING.md

- config/index.md
> docs: fix globalModulePaths type #47

- CONTRIBUTING.md
移行前のリポジトリ名になっている箇所を修正
（README は他の PR で修正済み）
> 旧リポジトリ名・リンクを修正

- blog/announcing-vite2.md
resolves #66
Cherry picked from https://github.com/vitejs/vite/commit/a68861f9a6ea09196125edde54cc6e68f31ccebe
> chore: typo in vite 2 announcement post (#66)

- guide/migration.md
> Translate "Migration from v1"

- config/index.md
- guide/backend-integration.md
> feat: modulepreload polyfill #50

- config/index.md
resolve #68 resolve #70 
vitejs/vite@d53dc92 と vitejs/vite@2faef0b の取り込みです
> Issue68+70

- guide/build.md
> Building for Production の翻訳

- package.json
- yarn.lock
close #6 
コミット時、ステージングファイルに対して textlint のタスクを実行するようにしました
> コミット時に textlint 実行

- guide/static-deploy.md
> apply vitejs/vite@0209086

- guide/backend-integration.md
> apply vitejs/vite@55bcc3f

- config/index.md
> Config ページ Server Options 後半の翻訳

- config/index.md
> Config ページ Build Options 後半の翻訳

- guide/static-deploy.md
> apply vitejs/vite@7232677

- guide/using-plugins.md
resolve #85
vitejs/vite@0aaca23 の適用です
> apply vitejs/vite@0aaca23

- config/index.md
resolve #86 
vitejs/vite@b010678 の対応です
> apply vitejs/vite@b010678

- guide/static-deploy.md
resolve #87
vitejs/vite@4776114 の対応です
> apply vitejs/vite@4776114

- config/index.md
- guide/ssr.md
resolve #88 
vitejs/vite@963387a の対応です
> apply vitejs/vite@963387a

- guide/dep-pre-bundling.md
resolve #93 
vitejs/vite@4c7af0a の対応です
> apply vitejs/vite@4c7af0a

- config/index.md
resolve #94 
vitejs/vite@cb90de0 の対応です
> apply vitejs/vite@cb90de0

- guide/features.md
resolves #95 
vitejs/vite@c287c20 の対応です
差分取り込み https://github.com/vitejs/docs-ja/commit/731ec582b5f1787a73c1a317826821d1198264f7 と翻訳 https://github.com/vitejs/docs-ja/commit/426da308d2d17500f165f238fcb31dde892976ff でコミット分けてます
> apply vitejs/vite@c287c20

- config/index.md
resolves #99 
vitejs/vite@f61ec46 の対応です
差分取り込み https://github.com/vitejs/docs-ja/commit/9781e07ed5b2f986e8ce47e2d53ca19451a00ae8 と翻訳 https://github.com/vitejs/docs-ja/commit/4744d12475e21f86ff33926d55dc9c1d80dd3cb5 でコミット分けてます
> apply vitejs/vite@f61ec46

- guide/api-plugin.md
resolves #105 
vitejs/vite@f19282f の対応です
差分取り込み 45c6d0d と翻訳 2968041 でコミット分けてます
> apply vitejs/vite@f19282f

- guide/index.md
resolve #106 
vitejs/vite@3392a8a の対応です
> apply vitejs/vite@3392a8a

- config/index.md
resolves #111 
vitejs/vite@b61b044 の対応です
差分取り込み 78e4e83 と翻訳 b1ffba5 でコミット分けてます
> apply vitejs/vite@b61b044

- guide/env-and-mode.md
> apply vitejs/vite@8926c96

- config/index.md
>  apply vitejs/vite@6f2dea2

- guide/index.md
resolves #135 
本家の差分は多いですが、こちらに関係あるのは1つだけでした
> apply vitejs/vite@3e1cce0

- guide/index.md
resolves #136 
ドキュメント関連の変更は1ファイルのみ
> apply vitejs/vite@d66ea0f

- guide/assets.md
> apply vitejs/vite@fc232d6

- config/index.md
resolves #153
ドキュメントの変更は1ファイルのみ。
取り込みと翻訳でコミットを分けてあります。
> apply vitejs/vite@b17444f

- guide/features.md
resolves #160 
vitejs/vite@9dbf20b の適用
> docs: Add defineConfig import in features.md

- guide/features.md
resolves #165 
vitejs/vite@ea0c221 の取り込みと翻訳です
> docs: add a workaround to `isolatedModules: true`

- guide/index.md
resolves #161 
vitejs/vite@d3aa321 の適用
---
resolves #162 
vitejs/vite@9afc2e7 の適用
> docs: add pnpm dlx example

- guide/api-javascript.md
resolves #166 
vitejs/vite@9af4f7c の適用
> docs: update api-javascript build base

- guide/index.md
- guide/static-deploy.md
resolves #173 
vitejs/vite@22873a7 の適用
> refactor: normalize scripts and commands naming

- guide/index.md
resolves #177 
vitejs/vite@484aad5 の適用
> chore: format

- guide/env-and-mode.md
resolves #178 
vitejs/vite@012ab61 の適用
> docs(env): mention vite/client.d.ts

- guide/static-deploy.md
resolves #190 
vitejs/vite@4d3bfae の適用
> docs: update static deploy docs for firebase

- config/index.md
- guide/api-javascript.md
resolves #196
vitejs/vite@ff755eb の取り込みと翻訳です
---
https://github.com/vitejs/vite/commit/211f183#diff-f7d4a01431aa2057a8d0c4ff1b1c233af89820b533c5fe3a64bc813eee69bab0 のインデント変更も本 PR で対応
> feat: preview config

- config/index.md
- guide/api-javascript.md
- guide/api-plugin.md
- guide/index.md
- guide/static-deploy.md
resolves #199 
vitejs/vite@a473570 の取り込みと翻訳です
> docs: dev and serve aliases

- guide/static-deploy.md
resolves #200 
vitejs/vite@7495074 の取り込みです
> docs: update static-deploy.md

- config/index.md
resolves #201
vitejs/vite@a44f480 の取り込みと翻訳です
> docs: add build.ssr in config/index.md

- config/index.md
resolves #209
vitejs/vite@9666446 の取り込みと翻訳です
> fix(ssr): skip dedupe require in esm

- config/index.md
resolves #211 
vitejs/vite@dcaaa0f の取り込みと翻訳です
> docs: add tip Note for build.cssCodeSplit

- guide/api-javascript.md
resolves #216 
vitejs/vite@1425a16 の取り込みと翻訳です
> feat(dev): expose restart function on ViteDevServer

- guide/api-plugin.md
resolves #210
vitejs/vite@04016df の取り込みと翻訳です
> docs: virtual modules internal convention

- config/index.md
resolves #227 
vitejs/vite@efec70f の取り込みと翻訳です
vitejs/vite@ae3a443 のうち、改行削除のみ適用
> docs: add optimizeDeps.esbuildOptions & remove optimizeDeps.keepName

- guide/ssr.md
resolves #237 
vitejs/vite@c768ffd の取り込みです
> docs(ssr): add server.js entry to folder structure

- guide/ssr.md
resolves #238 
vitejs/vite@4ece719 の取り込みと翻訳です
> docs(ssr): update middlewareMode comment

- .vitepress/config.js
resolves #29 
各ページ下部の `Suggest changes to this page` が本家へのリンクになっているので修正しました
> GitHub リンク修正

- config/index.md
resolves #247 resolves #248
vitejs/vite@8e65bab, vitejs/vite@80e8e93 の取り込みと翻訳です
> docs(config): note for TS + define [ci skip]

- config/index.md
- guide/api-javascript.md
- guide/env-and-mode.md
> intellisense の訳を統一

- guide/features.md
resolves #252 
vitejs/vite@1a6e2da の取り込みと翻訳です
> docs: typescript tips for using Type-Only Imports and Export

- guide/features.md
resolves #254 
vitejs/vite@44bb4da の取り込みです
> chore(deps): update to esbuild fixed at 0.14.3

- guide/env-and-mode.md
resolves #256
vitejs/vite@d8502e2 の取り込みと翻訳です。
> docs: add override rule for the env

- config/index.md
resolves #263 
vitejs/vite@133fcea の取り込みと翻訳です
> feat(worker): support worker format, plugins and rollupOptions

- config/index.md
resolves #265 
vitejs/vite@6408a3a の取り込みです
> feat: add customResolver option to resolve.alias

- config/index.md
resolves #271
vitejs/vite@8eb9e10 の取り込みと翻訳です
> docs: notes vite.config replace __dirname/__filename

- guide/features.md
- guide/index.md
- guide/using-plugins.md
resolves #272
vitejs/vite@e6b06e5 の取り込みです
> docs: align npm commands to other pms (create and add)

- config/index.md
resolves #277
vitejs/vite@0e164f8 の取り込みです
> feat: add lerna workspace support to searchForWorkspaceRoot

- guide/env-and-mode.md
resolves #278
vitejs/vite@9631e6a の取り込みです
> docs: serve runs in development mode

- guide/ssr.md
resolves #279
vitejs/vite@6b6ad70 の取り込みです
> docs: delegate error handling to express’s error handler

- .vitepress/theme/sponsors.json
resolves #291
Cherry picked from https://github.com/vitejs/vite/commit/3311686bbcc12481495374c58cd1bc054d2429b8
> chore: remove cancelled sponsor (#291)

- guide/static-deploy.md
resolves #289 
vitejs/vite@7418fe5 の取り込みと翻訳です。
> docs: Update deployment documentation for Vercel

- guide/static-deploy.md
resolve #299 
https://github.com/vitejs/vite/commit/a4a45e7e190b2a815a186121dac852340f80cc22 の取り込みと翻訳です。
> docs: add deployment steps for Netlify

- guide/static-deploy.md
resolve #302
https://github.com/vitejs/vite/commit/f63a72e77214ea31884680a3c5facf4fcee5d226 の取り込みです
> docs: rename empty git repo from master to main

- config/index.md
resolve #309
vitejs/vite@e234956 の取り込みです
> docs: add backticks

- guide/features.md
resolve #310 
vitejs/vite@4120908 の取り込みと翻訳です。
> docs: import.meta.glob support ?raw

- guide/api-javascript.md
resolve #320 
https://github.com/vitejs/vite/commit/c703a3348adeaad9dc92d805a381866917f2a03b の反映です
> feat: add fixStacktrace option to ssrLoadModule

- config/index.md
resolve #321 
https://github.com/vitejs/vite/commit/ce07a0ad6a2323fa3619a6e4de59fa792a988e21 の取り込みと翻訳です。
> feat(config): hmr add disable port config

- config/index.md
resolve #359 
https://github.com/vitejs/vite/commit/f44859379277b7a3e99529be275022733dc69ef1 の反映です
> docs: vite only replace __dirname, __filename, import.meta.url in cjs

- guide/features.md
resolve #360 
https://github.com/vitejs/vite/commit/4e0b61593a0eba97a901f996619c5e1aae4a7b68 の反映です
> docs: classic worker

- guide/api-hmr.md
- guide/api-plugin.md
> feat(dev): expose APIs for client-server communication

- guide/api-plugin.md
resolve #384
vitejs/vite@a89ea52 の反映です
> docs: update plugin example

- guide/api-plugin.md
resolve #385
https://github.com/vitejs/vite/commit/c02537b5b2ac5e39313601cc22530ef6201239b9 の反映です
> docs: improve virtual module examples

- config/index.md
resolve #324
https://github.com/vitejs/vite/commit/6cb0647834762bca9aa0cef542719882b42c2cf0 の適用です
> warning box

- guide/backend-integration.md
resolve #348
vitejs/vite@bf57c53 の反映です
> docs: remove vite client script

- guide/features.md
resolve #391 
https://github.com/vitejs/vite/commit/788d2ec1dc9853be4ecdef67d1a458a2b46ec9bf の反映です
> docs: explain skipLibCheck

- plugins/index.md
resolve #394 
https://github.com/vitejs/vite/commit/a7fd41660b06d258687a54fe73fef118bd73e1ca の反映です。
> docs: add link to "Using Plugins" from Plugins section

- config/index.md
resolve #345
https://github.com/vitejs/vite/commit/6608bd04af033717184cfff0074b2d9661db8804 の反映です
> docs: clarify postcss-load-config

- guide/api-hmr.md
resolve #399 
https://github.com/vitejs/vite/commit/72abe488b5ce52d21977c9ba35d6c590e47dbe05 の反映です
> docs(api-hmr): update hmr hot type

- guide/features.md
resolve #403 
https://github.com/vitejs/vite/commit/3edd1af56e980aef56641a5a51cf2932bb580d41 の反映です
> docs: update link to postcss-nesting repo

- config/index.md
resolve #404 
https://github.com/vitejs/vite/commit/5c1ee5abf987e25bd39d5af8013ed907a33d4d14 の反映です
2回目のコミットメッセージが、対応内容と無関係なものになってしまってしまいました。ご容赦ください🙇‍♂️
> docs: server.origin config trailing slash

- config/index.md
resolve #405
https://github.com/vitejs/vite/commit/206e1f2cd48b86396f57338ad494da3e1939b647 の反映です
> docs: clarify loadEnv

- config/index.md
- guide/build.md
resolve #413
https://github.com/vitejs/vite/commit/34df3075fce5bf71f4f69335bb6811731b1cadb0 の反映です。
> fix(lib): use proper extension

- guide/env-and-mode.md
resolve #415 
https://github.com/vitejs/vite/commit/0e67fe8ae23d4e21db578d9a18a63861e1cdade0 の反映です。
> fix: vite client types

- .vitepress/config.ts
resolve #422
vitejs/vite@ed4c759 の反映です
> docs: version selector

- README.md
- config/index.md
- guide/api-plugin.md
- guide/backend-integration.md
- guide/ssr.md
resolve #432
vitejs/vite@1cc2e2d の反映です
> feat!: vite dev default port is now 5173

- config/index.md
resolve #346
vitejs/vite@c6c2fbb の反映です
> docs: clarify preprocessor options extension

- config/index.md
resolve #364
vitejs/vite@81d7dd2 の反映です
> docs: add css.devSourcemap option

- guide/api-plugin.md
resolve #329 
vitejs/vite@cf6c817 の取り込みと翻訳です
> docs: clarify rollup plugin order

- guide/build.md
resolve #334
vitejs/vite@cb10ebf の取り込みと翻訳です
> docs(lib): show example entry file

- config/index.md
resolve #347
vitejs/vite@c2ab324 の反映です
> docs: add missing server.headers + server.base

- config/index.md
resolve #350
vitejs/vite@3ee04c0 の反映です
> fix: use hmr port if specified

- config/index.md
resolve #349
vitejs/vite@7998807 の反映です
> docs: clarify deprecated exports key end with /

- guide/api-plugin.md
resolve #421 
https://github.com/vitejs/vite/commit/20ea9999765ea372c20acc39e05cd81b98c9f6fe の反映です
> feat: new hook configurePreviewServer

- guide/features.md
resolve #423 
https://github.com/vitejs/vite/commit/330e0a90988509454e31067984bf0cdbe2465325 の反映です
> feat!: rework import.meta.glob

- config/index.md
resolve #425 
https://github.com/vitejs/vite/commit/d7c04e8a0106de857b4e13d35631699d1393f804 の反映です。
> docs(config-file): update tip note about string replace

- config/index.md
resolve #427 
https://github.com/vitejs/vite/commit/b2c029a086de135bbb04bbe0e35c0a3b4526900e の反映です。
> docs: mention middlewares in server.proxy config

- config/index.md
- guide/features.md
resolve #429 
https://github.com/vitejs/vite/commit/774bd286c6666878003ac34f7e256c539a84f9bd の反映です。
> docs: explain dynamic import

- config/index.md
resolve #437 
https://github.com/vitejs/vite/commit/66efd69a399fd73284cc7a3bffc904e154291a14 の反映です。
> build!: bump targets

- guide/features.md
resolve #443 
https://github.com/vitejs/vite/commit/75c3bf65694bc89b395e03dabb81721871d24a9c の反映です。
> feat(wasm): new wasm plugin (.wasm?init)

- config/index.md
- guide/api-javascript.md
resolve #445 
https://github.com/vitejs/vite/commit/3f832bc8f5d2c605d7fae9088a9a82a45c54a052 の反映です。
> docs: remove experimental from stabilized apis

- guide/assets.md
resolve #386
vitejs/vite@09c4fc0 の反映です
> docs: warning for new URL(url, import.meta.url)

- .vitepress/config.ts
- .vitepress/theme/custom.css
- .vitepress/theme/index.js
- .vitepress/theme/styles/vars.css
- index.md
- package.json
- yarn.lock
> Revert "docs: use vitepress next"

- config/index.md
- guide/build.md
resolve #448 
https://github.com/vitejs/vite/commit/06675852b6de1d45600f31183f44c8efebe0c38e の反映です。
> docs: update lib mode example

- guide/features.md
resolve #449 
https://github.com/vitejs/vite/commit/9e2a1ea7a11a1f86e3b5a5f0a3eaf71a6a7a592e の反映です。
`packages`の変更は、こちらの翻訳リポジトリにはないため反映してません。
> fix(plugin-react): broken optimized deps dir check

- config/index.md
- guide/ssr.md
resolve #450 
https://github.com/vitejs/vite/commit/d7cba466febd5127e82573f69b1f7b866517a299 の反映です。
このPRも`packages`の変更は反映不要と判断し、反映してません。
> feat: spa option, preview and dev for MPA and SSR apps

- config/index.md
- guide/assets.md
- guide/build.md
- guide/index.md
resolve #439 
https://github.com/vitejs/vite/commit/e68c25cf464428fb42e622fd3749f0daf1b943ab の反映です
> docs: update for default target change

- guide/static-deploy.md
resolve #476 
https://github.com/vitejs/vite/commit/80e44a8fbb2677396c7ef557460e54979dc04f59 の反映です。
> docs: update Heroku deployment instructions

- index.md
> chore: fix typo

- guide/api-plugin.md
resolve #493 
https://github.com/vitejs/vite/commit/c5c424a93cf97e254dae46a35ad6de46ec350a16 の反映です。
> feat: expose createFilter util

- config/worker-options.md
- guide/features.md
resolve #495 
https://github.com/vitejs/vite/commit/c0c5e1a26d2099acd65a062fcfc790b85dc94db5 の反映です。
> docs: worker related notes

- config/index.md
resolve #489 
https://github.com/vitejs/vite/commit/51e9195fe94657e7ab14a22a0e7de338ad0724fd の反映です。
> feat: better config __dirname support

- config/index.md
resolve #497
https://github.com/vitejs/vite/commit/ed12ed1b1d40ae106fdc9403fd581f316b20f560 の反映です。
> docs: update config jsdoc style

- .vitepress/config.ts
- package.json
- yarn.lock
resolve #496 
https://github.com/vitejs/vite/commit/e8eb0b6db11f28a8d45a50235ad088620e3ca310 の反映です。
> docs: update vitepress to alpha.2

- config/dep-optimization-options.md
- config/server-options.md
- guide/migration.md
resolve #499
https://github.com/vitejs/vite/commit/f520a54b5ba82468f7039379149c9aa0ff06e0af の反映です。
> refactor: rename force to optimizeDeps.force

- guide/ssr.md
> fix: 「サーバサイドレンダリング」ページの翻訳の修正

- .vitepress/config.ts
> fix: language change

- .vitepress/config.ts
resolves #572
Cherry picked from https://github.com/vitejs/vite/commit/631e26de43283b4ce1fcca7bcb42ff9008115a82
> docs: version toggle label (#572)

- .vitepress/config.ts
resolves #583
Cherry picked from https://github.com/vitejs/vite/commit/8e0308bee847e5a1a126a86585ff102583e81c3c
> docs: add `appId` in vitepress config (#583)

- config/shared-options.md
resolve #503
https://github.com/vitejs/vite/commit/caa8a58e5bd252973dd4a9da6bb1d375aa1700e9 の反映です
> feat: support async plugins

- guide/index.md
- public/voice.svg
- vite.config.ts
resolve #508
vitejs/vite@a52c6c8 の反映
> docs: tweak voice.svg

- config/server-options.md
- config/shared-options.md
- guide/ssr.md
resolve #504
https://github.com/vitejs/vite/commit/14db47397b0a9f99923a326bbd23c2df7c5b6745 の反映です
> feat!: appType (spa, mpa, custom), boolean middlewareMode

- config/preview-options.md
- config/server-options.md
resolve #505
https://github.com/vitejs/vite/commit/9a1c1aee56b3ab67fa9f019ccb647eef3e31f5f7 の反映です
> docs: improve wildcard host note

- .vitepress/config.ts
resolve #525
vitejs/vite@7e899d0 の取り込みです
> chore: v3 beta release notes

- guide/index.md
resolve #531
vitejs/vite@8108b1b の反映です
> docs: correct pnpm command

- guide/migration.md
resolve #509
https://github.com/vitejs/vite/commit/3b41a8eb1006ae636e2b01b8416327e001625df4 の反映です
> fix: disable inlineDynamicImports for ssr.target = node

- config/server-options.md
- guide/migration.md
resolve #511 
https://github.com/vitejs/vite/commit/eb52d36a2cbdf6182691ac3ec5cb6d28d1ac73ad  の反映です
> feat: print resolved address for localhost

- guide/build.md
resolve #514 
https://github.com/vitejs/vite/commit/8ef733368fd6618a252e44616f7577f593fd4fbc の反映です
> feat: experimental.buildAdvancedBaseOptions

- guide/migration.md
resolve #518
https://github.com/vitejs/vite/commit/3f9e5d49dfeb25ee22423fb5d180fe63b1c23c41 の反映です
> docs: add #8626 to migration guide

- guide/api-hmr.md
resolve #512
https://github.com/vitejs/vite/commit/cf87882130e991fa4f26782a462c503faf8e5f9f の反映です
型と参考コードの変更のみです 👍
> refactor: type client maps

- config/shared-options.md
resolve #542 
vitejs/vite@6886078 の反映です
> feat: accept AcceptedPlugin type for postcss plugin

- guide/migration.md
resolve #543
vitejs/vite@1a498f7 の反映です
> docs: fix the wasm example in "migration from v2"

- guide/ssr.md
resolve #547
vitejs/vite@8970f16 の反映です
> docs: fix typo

- guide/migration.md
resolve #551
vitejs/vite@188f188 の反映です
> feat: improved cold start using deps scanner

- guide/build.md
resolve #526
https://github.com/vitejs/vite/commit/6105471fa304891dc2b09472ce6d92f39ca4c388 の反映です
> fix: typo on https example

- config/build-options.md
- config/shared-options.md
resolve #532
https://github.com/vitejs/vite/commit/8b77695870d16e030392fe2ef9826140e61c6e82 の反映です
> feat: respect esbuild minify config

- guide/api-plugin.md
resolve #539
https://github.com/vitejs/vite/commit/e53c029ef645d1d91c284799489a11d1f41303ec の反映です
> docs: clarification `transformIndexHtml`

- guide/build.md
resolve #541
https://github.com/vitejs/vite/commit/895a7d66bc93beaf18ebcbee23b00fda9ca4c33c の反映です
> feat: experimental.renderBuiltUrl (revised build base options)

- guide/comparisons.md
resolve #546
https://github.com/vitejs/vite/commit/cad27ee8c00bbd5aeeb2be9bfb3eb164c1b77885 の反映です
> docs: simplify Snowpack comparison

- config/index.md
resolve #548
resolve #552
https://github.com/vitejs/vite/commit/b6d655ac73631bfdcc41c4534652c864dcc00b76, https://github.com/vitejs/vite/commit/722f5148ea494cdc15379d3a98dca0751131ca22  の反映です
また、行が一つずれていたのでその修正も含んでいます 01271dbca1b1d2508ce31895778fc0b532338f5c (必要があれば別のPRに切り出します)
> feat: ssrBuild flag in config env, fix: ssrBuild is optional, avoid breaking VitePress

- guide/ssr.md
resolve #553
https://github.com/vitejs/vite/commit/9d28ffd3410a3ea2b739cce31e845f59cebd3cc6 の反映です
> docs(ssr): specify the use of express.Router

- guide/static-deploy.md
resolve #556
resolve #558 
https://github.com/vitejs/vite/commit/df5688cae266bd0dacb6b5b7bcd0348e42bc61dd, https://github.com/vitejs/vite/commit/bef378d4a0737a8e8f4d75171ec919a758d2833d の反映です
> docs: add Cloudflare Pages to deploy options, docs: update Cloudflare pages option (updates: #8927)

- .vitepress/config.ts
- _data/team.js
- team.md
resolve #563
vitejs/vite@519f7de の反映です
> docs: add team page

- config/server-options.md
- guide/migration.md
resolve #559
resolve #560
https://github.com/vitejs/vite/commit/5c6cf5a2a6577fb8e8ecc66a0411143af3fed042, https://github.com/vitejs/vite/commit/f8c8cf272345364e8a6181725335e95b957ba8c4 の反映です
> refactor!: move basic ssl setup to external plugin, fix #8532, refactor: opt-in optimizeDeps during build and SSR

- guide/api-javascript.md
resolve #562
https://github.com/vitejs/vite/commit/05b17dfcdf0c6d792a7ec5d9cf9a11e17ac79b6c の反映です
#646 で行がずれるため、行数がずれています
> docs: update api-javascript

- .vitepress/config.ts
- _data/team.js
- team.md
> team ページの翻訳

- config/index.md
resolve #587
vitejs/vite@1e078ad の反映です
> feat: allow declaring dirname

- guide/env-and-mode.md
resolve #588
vitejs/vite@344642a の反映です
> docs: fix broken link to envPrefix config option

- guide/backend-integration.md
resolve #596
vitejs/vite@aa0b921 の反映です
> docs: add vite client script for backend integration

- config/server-options.md
- guide/api-javascript.md
- guide/api-plugin.md
- guide/assets.md
- guide/build.md
- guide/env-and-mode.md
- guide/features.md
- guide/index.md
- guide/migration.md
- guide/ssr.md
- guide/static-deploy.md
resolve #561
resolve #581
https://github.com/vitejs/vite/commit/07aef1b4c02a64732b31b00591d2d9d9c8025aab, https://github.com/vitejs/vite/commit/0ef8303806ed2b4961c9010cda0fe06cca43a2be の反映です
一か所、行数の修正をしています
> docs: cleanup changes

- config/server-options.md
- guide/migration.md
resolve #571
https://github.com/vitejs/vite/commit/d5d41a6688250c9b67bcfe326d69d0f9ed811a20 の反映です
> docs: improve server.host desc in migration guide

- guide/build.md
resolve #585
https://github.com/vitejs/vite/commit/60fa6ba082c50d57ec4abecb196573f4100636d2 の反映です
> docs: update library mode info

- .vitepress/config.ts
- package.json
- yarn.lock
resolve #601
resolve #602
resolve #603
> docs: show deployed version

- .vitepress/config.ts
resolve #612
vitejs/vite@b26b84b の反映です
> docs: update algolia appId and key

- blog/announcing-vite3.md
- config/build-options.md
- guide/build.md
- guide/index.md
- guide/migration.md
resolve #609
resolve #613
https://github.com/vitejs/vite/commit/b82ee5d39b8c8de1d3f9a2b4531b58634582ef00, https://github.com/vitejs/vite/commit/8469bf0a5e38cbf08ec28e598ab155d339edc442  の反映です
> docs: update browser baseline features, docs: update broken link for import.meta

- .vitepress/config.ts
resolves #672
Cherry picked from https://github.com/vitejs/vite/commit/a206f16912c5dfd2c92b5ca35fd641fc4f2506e3
> docs: set browser meta theme-color (#672)

- .vitepress/config.ts
- config/server-options.md
- guide/troubleshooting.md
resolve #627
resolve #631 
https://github.com/vitejs/vite/commit/c91813971944ea3263062e8955267453feef88ba, https://github.com/vitejs/vite/commit/46264ffaa1ae011e2a087f1a23ea99832ffd9020 の反映です
> docs: add troubleshooting page, docs: ESM is always strict mode

- guide/features.md
resolve #649
https://github.com/vitejs/vite/commit/1983cf43d4da92d40b1f96dff0a44def044f9130  の反映です
> docs: override `vite/client` type

- config/shared-options.md
resolve #611
https://github.com/vitejs/vite/commit/b2a493131873422f96089601669ab104d68e80a7  の反映です
> docs: `resolve.alias` for SSR externalized deps

- guide/build.md
resolve #679
vitejs/vite@6ad6734 の反映です
> docs: fix renderBuiltUrl example

- config/preview-options.md
resolve #666
vitejs/vite@89dd31c の反映です
> docs(preview): replace dev server references

- guide/static-deploy.md
resolve #677
https://github.com/vitejs/vite/commit/a6b12f8c4608e945ca21811dce6d94c26cb4d7b6 の反映です
> docs: add git option for netlify deployment

- guide/static-deploy.md
resolve #678
https://github.com/vitejs/vite/commit/27a20a5fd07c352c2f56b9f1e7a9955f349f0d2f の反映です
#677 と同じファイルのため行数がずれています
> docs: add Render deployment instructions

- guide/troubleshooting.md
resolve #682
https://github.com/vitejs/vite/commit/e8b61bb3cac6c9c3ef3fa33e43440cc646473696 の反映です
> feat: show warning on 431 response

- config/build-options.md
- config/server-options.md
resolve #683
https://github.com/vitejs/vite/commit/afbb87d1f85fec29598592a1d3f7610c8ccc8fcc の反映です
> docs: update WSL2 watch limitation explanation

- guide/ssr.md
resolve #685
https://github.com/vitejs/vite/commit/095e92041ebe638da95ae8d507d13a34d8f63f62 の反映です
> docs(ssr): note linked deps no external

- guide/static-deploy.md
resolve #718
vitejs/vite@834a382 の反映です
> docs: update `git checkout -b main` as `git checkout -B main`

- .vitepress/config.ts
resolves #721
Cherry picked from https://github.com/vitejs/vite/commit/f248e6510ba332256d4e87ffda589ab64c6ac3d4
> docs: add fathom analytics (#721)

- guide/static-deploy.md
resolve #698
vitejs/vite@aebfd9c の反映です
> docs: remove heroku instructions

- guide/api-javascript.md
resolve #696
vitejs/vite@c3f6731 の反映です
> feat: stabilize server.resolvedUrls

- config/preview-options.md
resolve #697
vitejs/vite@0d20eae の反映です
> fix(preview): send configured headers

- config/server-options.md
resolve #699
vitejs/vite@df560b0 の反映です
> perf: cache compiled glob for server.fs.deny

- config/shared-options.md
resolve #701
vitejs/vite@533d13c の反映です
> fix: respect mainFields when resolving browser/module field

- guide/static-deploy.md
resolve #702
vitejs/vite@0f7353b の反映です
> docs: place .nojekyll when deploying to GitHub Pages

- guide/api-plugin.md
resolve #703
vitejs/vite@da632bf の反映です
> refactor(types): bundle client types

- guide/troubleshooting.md
resolve #704
vitejs/vite@71eaacf の反映です
> docs: add trouble shooting section about file protocol

- config/build-options.md
resolve #705
vitejs/vite@e223f84 の反映です
> feat: build.modulePreload options

- guide/api-hmr.md
resolve #714
vitejs/vite@fb8ab16 の反映です
> feat: support import.meta.hot.invalidate

- guide/api-plugin.md
resolve #715
vitejs/vite@291174d の反映です
> refactor(types): simplify type exports

- config/build-options.md
- guide/build.md
resolve #716 
vitejs/vite@65a0fad の反映です
> feat(lib): allow multiple entries

- guide/api-hmr.md
resolve #717
vitejs/vite@c48bda5 の反映です
> docs: fix code example

- guide/api-javascript.md
resolve #723 
vitejs/vite@8328011 の反映です
> feat(server): invalidate module with hmr

- guide/features.md
resolve #724
vitejs/vite@f542727 の反映です
> feat: update esbuild compilation affecting fields

- config/build-options.md
resolve #726
vitejs/vite@4f4a39f の反映です
> feat(build): experimental copyPublicDir option

- guide/env-and-mode.md
resolve #728
vitejs/vite@96bd10a の反映です
> docs: add note to use dotenv-expand

- guide/features.md
resolve #729 
vitejs/vite@5c4c58f の反映です
> docs: adding postcss plugin load order explanation

- config/server-options.md
resolve #730
vitejs/vite@ff3eacf の反映です
> docs: expand server.proxy description

- guide/troubleshooting.md
resolve #731
vitejs/vite@cb84f37 の反映です
> docs: Added additional workaround steps for stalled requests

- guide/api-hmr.md
resolve #734
vitejs/vite@0d73473 の反映です
> feat(hmr): invalidate message

- config/shared-options.md
resolve #735
vitejs/vite@a03860f の反映です
> docs: update appType docs

- guide/api-hmr.md
resolve #736
vitejs/vite@f40c18d の反映です
> chore(client): expose hot.prune API

- guide/api-hmr.md
resolve #737
vitejs/vite@f777b55 の反映です
> refactor(client): simplify fetchUpdate code

- plugins/index.md
> chore(plugins): fix missing links

- guide/dep-pre-bundling.md
resolve #740
vitejs/vite@4fb7ad0 の反映です
> feat(optimizer): support patch-package

- guide/ssr.md
resolve #741
vitejs/vite@d76db0c の反映です
> docs: remove extra space

- guide/env-and-mode.md
resolve #743
vitejs/vite@8b3d656 の反映です
> fix(config)!: support development build

- _data/team.js
resolve #782
vitejs/vite@962e593 の反映です
> docs: update team

- guide/api-plugin.md
resolve #752
vitejs/vite@1db52bf の反映です
> feat: align object interface for transformIndexHtml hook

- blog/announcing-vite3.md
- guide/features.md
- guide/ssr.md
resolve #773, resolve #774 
vitejs/vite@5935619, vitejs/vite@3cd86be の反映です
> refactor: move framework plugins out of core

- guide/api-hmr.md
resolve #775 
vitejs/vite@e257e3b の反映です
> chore(client)!: remove never implemented hot.decline

- .vitepress/config.ts
- .vitepress/theme/components/AsideSponsors.vue
- .vitepress/theme/composables/sponsor.ts
- .vitepress/theme/index.ts
- config/build-options.md
- config/dep-optimization-options.md
- config/index.md
- config/preview-options.md
- config/server-options.md
- config/shared-options.md
- guide/api-hmr.md
- guide/api-javascript.md
- guide/api-plugin.md
- guide/backend-integration.md
- guide/build.md
- guide/dep-pre-bundling.md
- guide/features.md
- guide/migration.md
- guide/ssr.md
- guide/using-plugins.md
resolve #776
vitejs/vite@134ce68 の反映です
> chore: enable prettier trailing commas

- guide/index.md
resolve #787 
vitejs/vite@348146f の反映です
> feat(create-vite): add react-swc templates

- .vitepress/config.ts
- guide/migration.md
resolve #789
vitejs/vite@e57ebba の反映です
> docs: migration from v3 guide

- blog/announcing-vite4.md
- guide/migration.md
resolve #790
vitejs/vite@897f69f の反映です
> docs: add env var section

- plugins/index.md
resolve #794
vitejs/vite@8241758 の反映です
> docs: add plugin-react-swc to official plugins list

- guide/assets.md
resolve #796 
vitejs/vite@388adf5 の反映です
> docs: add client types hint in static assets guide

- guide/migration.md
resolve #797 
vitejs/vite@85fefad の反映です
> docs(migration): add section for build node env

- config/worker-options.md
resolve #804
vitejs/vite@44fb01a の反映です
> docs: specify that 'worker' means 'web worker'

- _data/team.js
resolves #813
Cherry picked from https://github.com/vitejs/vite/commit/0a07686f651b8583e8091ada146b96576e8501e9
> chore: add dominikg to the Vite team page (#813)

- guide/build.md
resolve #811
vitejs/vite@394148e の反映です
> docs: update extensions generated in library mode

- guide/troubleshooting.md
resolve #812
vitejs/vite@2059319 の反映です
> docs: troubleshooting issues with self-signed SSL certs

- config/preview-options.md
- config/server-options.md
resolve #819
vitejs/vite@8972868 の反映です
> feat: support BROWSER and BROWSER_ARGS in env file

- config/server-options.md
resolve #824
vitejs/vite@111ecbf の反映です
> docs: update server-options.md

- config/build-options.md
resolve #828
vitejs/vite@58314d2 の反映です
> docs: fix build-options default

- guide/ssr.md
resolve #835
vitejs/vite@f72fdc7 の反映です
> docs: ssr manifest can be used for 103 early hints

- plugins/index.md
resolve #836
vitejs/vite@8a40ea4 の反映です
> chore: add vite-plugin-vue2 to official plugins list

- config/build-options.md
- config/worker-options.md
- guide/api-plugin.md
- guide/build.md
- guide/troubleshooting.md
resolve #837
vitejs/vite@4bbebf3 の反映です
> docs: update rollup docs links

- config/build-options.md
resolve #838
vitejs/vite@9adb2a3 の反映です
> docs: update build-options.md

- config/preview-options.md
- config/server-options.md
resolve #839
vitejs/vite@9c4ca07 の反映です
> docs: change cors options object link

- .gitignore
- .vitepress/theme/styles/vars.css
- package.json
- yarn.lock
resolve #840
vitejs/vite@c5b935a の反映です
vitepress を上記コミット時のバージョンに合わせました
> docs: update vitepress

- .vitepress/config.ts
resolve #841
vitejs/vite@49203a7 の反映です
> docs: restore locale links

- guide/features.md
resolve #849
vitejs/vite@2fbce97 の反映です
> docs: fix generated output code for custom queries

- config/worker-options.md
resolve #850
vitejs/vite@c120afc の反映です
> docs: distinguish plugins config used for workers in build and serve

- guide/troubleshooting.md
resolve #851 
vitejs/vite@cc00b52 の反映です
> docs: add troubleshooting for browser compat

- .vitepress/config.ts
resolves #863
Cherry picked from https://github.com/vitejs/vite/commit/5364c901dca31d4a16dac288bcb55305949d10ae
> docs: add mastodon docs (#863)

- guide/troubleshooting.md
resolve #867 
vitejs/vite@c79582b の反映です
> docs(troubleshooting): add network stalled solution for ubuntu linux

- guide/static-deploy.md
resolve #868 
vitejs/vite@301f160 の反映です
> docs: update GitHub Pages documentation

- _data/team.js
resolves #876
Cherry picked from https://github.com/vitejs/vite/commit/4783468ad7103acd590457473de87669ff155dfc
> docs: update sodatea description (#876)

- guide/features.md
resolve #873
vitejs/vite@f2a5fcc の反映です
> docs: fix svg type override

- plugins/index.md
resolve #875
vitejs/vite@aab4f13 の反映です
> docs: precise plugin-react-swc build when using plugins

- config/dep-optimization-options.md
resolve #887 
vitejs/vite@59e9b07 の反映です
> docs(dep-optimization): add disabled API

- config/shared-options.md
resolve #888
vitejs/vite@8477b07 の反映です
> docs: added custom logger info

- guide/api-plugin.md
resolve #890
vitejs/vite@7b9df65 の反映です
> docs(api-plugin): update server-to-client example

- blog/announcing-vite2.md
- blog/announcing-vite3.md
- blog/announcing-vite4.md
resolves #893
Cherry picked from https://github.com/vitejs/vite/commit/b8cdc920a993fd67d9e97a2576896cc4351a1a83
> docs: add date to announcement blog posts (#893)

- guide/api-hmr.md
resolve #892 
vitejs/vite@8f57a18 の反映です
> docs(api-hmr): note intellisense for import.meta.hot

- guide/api-plugin.md
resolve #903
vitejs/vite@e421500 の反映です
> docs(api-plugin): note plugin options extended properties

- config/server-options.md
resolve #905
vitejs/vite@f875580 の反映です
> feat: add `sourcemapIgnoreList` configuration option

- .vitepress/config.ts
こんにちは。本レポに貢献しようと思い[貢献方法](https://github.com/vitejs/docs-ja/blob/main/CONTRIBUTING.md#%E8%B2%A2%E7%8C%AE%E6%96%B9%E6%B3%95)を見てIssueを探していたんですが、初っ端から大きな変更を加えることに少し不安を感じるので小さめのPRを送らせてもらいます。
今後アサインされていないIssueを通して貢献していければなと思っています。
> docs: update versionLinks, outlineTitle and docFooter

- config/server-options.md
resolve #912 
vitejs/vite@ab6ae07 の反映です
> fix: enforce absolute path for server.sourcemapIgnoreList

- guide/api-javascript.md
- guide/env-and-mode.md
- guide/features.md
resolve #913 
vitejs/vite@4f2c49f の反映です
ついでに未翻訳の見出しを修正
> feat(html): support env replacement

- config/server-options.md
resolve #914
vitejs/vite@dd7a2f1 の反映です
> docs: clarify server.sourcemapIgnoreList docs

- .vitepress/config.ts
resolves #927
Cherry picked from https://github.com/vitejs/vite/commit/805553640ac25c97b262e2d68ccca03ffe1be9d4
> chore: disable reactivityTransform in vitepress (#927)

- config/build-options.md
resolve #916
vitejs/vite@90431f2 の反映です
> feat(css): add build.cssMinify

- config/shared-options.md
resolve #917
vitejs/vite@f89f12a の反映です
> docs: add note about using define in envPrefix config

- _data/team.js
resolves #934
Cherry picked from https://github.com/vitejs/vite/commit/0f9ad6896ae93f79cc7ef6fbb2fd56047d719245
> docs: update dominikg team info (#934)

- guide/features.md
resolve #938 
vitejs/vite@363fa31 の反映です
> docs: rephrase configuration of Client Types

- config/server-options.md
resolve #939 
vitejs/vite@7ce9b00 の反映です
> docs: update x_google_ignoreList documentation url

- guide/troubleshooting.md
resolve #943
vitejs/vite@e6eed85 の反映です
> docs: troubleshooting on browser extension blocker

- _data/team.js
resolves #951
Cherry picked from https://github.com/vitejs/vite/commit/8c5f1d8a14393e212f0250aa7e0fcb2fb03a747f
> chore: add sheremet-va to the team (#951)

- guide/troubleshooting.md
resolve #944 
vitejs/vite@a2b7a51 の反映です
> docs: yarn link and outdated dependencies

- config/shared-options.md
resolve #945
vitejs/vite@ad358da の反映です
> docs: fix pnpm link

- guide/features.md
resolve #946
vitejs/vite@23b5979 の反映です
> docs: remove mention to deprecated vue-class-components

- guide/api-plugin.md
resolve #963 
https://github.com/vitejs/vite/commit/21dd28dd648b6d043eaad2f31efdd379e5134635 の反映です！
よろしくお願いします。
> docs: document /index.html as importer during dev

- .vitepress/config.ts
- releases.md
resolve #958
https://github.com/vitejs/vite/commit/ad1ae3ed6a32baf5d56823f8004555c68d3ad405 の反映です
> docs: releases page

- guide/features.md
resolve #970
vitejs/vite@0cbd818 の反映です
> docs: update features.md note about ESM imports in web workers

- .vitepress/theme/styles/vars.css
resolves #984
Cherry picked from https://github.com/vitejs/vite/commit/b93242e60351048f4faf54560ca6a7b97b2e7aca
> docs: adjust aside sponsors max width (#984)

- .vitepress/config.ts
resolves #993
Cherry picked from https://github.com/vitejs/vite/commit/93eed463089e2440ffc2859e6e58fffaca7376b7
> docs: link to ko translation (#993)

- guide/troubleshooting.md
resolve #988
https://github.com/vitejs/vite/commit/b9a6ba044f5f551c9d7966802caa1bec714eedb3 の反映です。
> docs: friendly ESM file require error

- guide/api-javascript.md
resolve https://github.com/vitejs/docs-ja/issues/987
https://github.com/vitejs/vite/commit/998512b66fcd810fd133c31e821c47757f86d7eb の反映です。
> docs: don't accept callback config

- config/server-options.md
resolve #981
https://github.com/vitejs/vite/commit/2872d5520a1a088a89effb155edf59d776a3ced3 の反映です。
> docs: accessing the server on WSL2 from your LAN

- config/server-options.md
resolve: https://github.com/vitejs/docs-ja/issues/989
https://github.com/vitejs/vite/commit/4a06e66130ee4701b9461081ab09ad88cadc5ac2 の反映です。
> docs: support files for `fs.allow`

- config/server-options.md
resolve: https://github.com/vitejs/docs-ja/issues/1001
https://github.com/vitejs/vite/commit/dc597bd913bad167e9f8398e4fb506131e96cadd の反映です。
> docs: remove deprecated config.server.base

- guide/api-hmr.md
resolve: https://github.com/vitejs/docs-ja/issues/1008
https://github.com/vitejs/vite/commit/eb751032d5b18b87e5a6639fcc640f74d352cd23 の反映です。
> docs: add WebSocket connections events

- guide/build.md
resolve: https://github.com/vitejs/docs-ja/issues/1014
https://github.com/vitejs/vite/commit/658283d4cf09295f99645e136b6429057bf2275b の反映です。
> docs(build): fix typo

- config/build-options.md
- config/shared-options.md
- guide/features.md
resolve: https://github.com/vitejs/docs-ja/issues/1019
resolve: https://github.com/vitejs/docs-ja/issues/1023
https://github.com/vitejs/vite/commit/94342e7a90d5995118a82ccaefda6641af207965 の反映です。
> docs: experimental Lightning CSS support

- guide/index.md
resolve: https://github.com/vitejs/docs-ja/issues/1027
https://github.com/vitejs/vite/commit/277e844c1a0cc729c387d9a16ef838835eb06f49 の反映です。
> docs: add solidjs templates

- guide/features.md
resolve: https://github.com/vitejs/docs-ja/issues/1034
https://github.com/vitejs/vite/commit/8a2a3e1e7f500a6c803187c965e49fe6cc5478b6 の反映です。
> docs: fix build.cssMinify link

- guide/static-deploy.md
resolve: https://github.com/vitejs/docs-ja/issues/1032
https://github.com/vitejs/vite/commit/fd1b7315852616a00156f79b413c0f2a0029e51b の反映です。
> docs(static-deploy): added deployment instructions for AWS with Flightcontrol

- guide/features.md
resolve: https://github.com/vitejs/docs-ja/issues/1045
https://github.com/vitejs/vite/commit/2c73d10ed2e18db6da892acdcfe1637b86d72599 の反映です。
> docs(wasm): add sections about Node.js and module access

- config/shared-options.md
resolve #1055
vitejs/vite@d179c01 の反映です
> docs: update esbuild link

- guide/troubleshooting.md
resolve: https://github.com/vitejs/docs-ja/issues/1051
https://github.com/vitejs/vite/commit/663201851bcef9ad75386d72f7f775407c4ada1d の反映です。
> docs: include vite-plugin-inspect in troubleshooting page

- .github/workflows/lint.yml
> GitHub Actions のパッケージ更新

- config/build-options.md
resolve #1062
vitejs/vite@443c235 の反映です
> feat: copyPublicDir out of experimental

- guide/env-and-mode.md
resolve: https://github.com/vitejs/docs-ja/issues/1054
https://github.com/vitejs/vite/commit/72d5d4d83310a7128daf3cf670659d20dd0c7941 の反映です。
> docs: clarify when import.meta.env.PROD is true

- guide/api-javascript.md
- guide/api-plugin.md
resolve: https://github.com/vitejs/docs-ja/issues/1053
https://github.com/vitejs/vite/commit/e0eb07c5d174456b19db81839383f39f3abb57fa の反映です。
> refactor!: merge PreviewServerForHook into PreviewServer type

- guide/api-javascript.md
resolve: https://github.com/vitejs/docs-ja/issues/1056
https://github.com/vitejs/vite/commit/094b7324827940ee02c8e4a9ccae5e25c236eecd の反映です。
> docs: add example for mergeConfig with a config in callback form

- guide/build.md
resolve: https://github.com/vitejs/docs-ja/issues/1069
https://github.com/vitejs/vite/commit/fe6cb93e9a47671fb9fbd06f72dd372a908ce74f の反映です。
> docs(library-mode): add advanced usage warning

- guide/index.md
resolve: https://github.com/vitejs/docs-ja/issues/1070
https://github.com/vitejs/vite/commit/65b690657f0f97ef7912f3f45002c725d4bcc989 の反映です。
> docs: remove npm@6 commands

- config/server-options.md
resolve: https://github.com/vitejs/docs-ja/issues/1075
https://github.com/vitejs/vite/commit/cd6bf29ca4b677ff0d6e2bf36416a65b1a6ffa21 の反映です。
> docs: update the proxy options link

- guide/api-javascript.md
resolve: https://github.com/vitejs/docs-ja/issues/1078
https://github.com/vitejs/vite/commit/1a2e5e6d9a6bb2531bf73be801c9778dbf39d51b の反映です。
> feat: export `server.bindCLIShortcuts`

- config/server-options.md
- guide/api-javascript.md
resolve #1096
vitejs/vite@af5a95e の反映です
> feat: allow passing down "null" to disable server watcher

- config/build-options.md
resolve #1101
vitejs/vite@884fc3d の反映です
> feat(terser): add `maxWorkers` option for terserOptions

- guide/env-and-mode.md
- guide/features.md
- package.json
- yarn.lock
resolve #1095
vitejs/vite@68638f7 の反映です
> fix(deps): update all non-major dependencies

- CONTRIBUTING.md
- package.json
> test スクリプト削除

- guide/troubleshooting.md
resolve #1099
vitejs/vite@404f30f の反映です
> feat!: deprecate cjs node api

- config/server-options.md
resolve #1100
vitejs/vite@fbfad21 の反映です
> docs: update server.watch info

- public/_redirects
resolve #1111 
vitejs/vite@a2e9fb5 の反映です
> docs: redirect vite.dev to vitejs.dev

- guide/static-deploy.md
resolve #1113
vitejs/vite@27bffc4 の反映です
> docs: update wrangler command

- guide/api-hmr.md
resolve #1119
https://github.com/vitejs/vite/commit/31333bbb77ce3bf4a34380a2f07f926330993cac の反映です
> feat: add off method to ViteHotContext

- guide/build.md
resolve #1124 
vitejs/vite@7e0f386 の反映です
> docs: change https://polyfill.io/v3/ to https://polyfill.io/

- config/server-options.md
resolve #1126
vitejs/vite@da80372 の反映です
> feat: add server.warmup option

- .vitepress/config.ts
resolves #1164
Cherry picked from https://github.com/vitejs/vite/commit/3a8d5a4df759eccef00302674f487b834d6cffe1
> docs: 🇩🇪 added german locale link to config.ts; (#1164)

- guide/ssr.md
resolve #1125 
vitejs/vite@02cd043 の反映です
> docs(ssr): update example projects

- guide/troubleshooting.md
resolve #1131
vitejs/vite@e5ee420 の反映です
> feat: postcss config `.cts` support

- config/worker-options.md
resolve #1132 
vitejs/vite@9d09dfe の反映です
> fix!: worker.plugins is a function

- guide/static-deploy.md
resolve #1141
vitejs/vite@cc9fb87 の反映です
> docs(static-deploy): bump gh-pages action to v2

- guide/static-deploy.md
oad-pages-artifact
resolve #1144
vitejs/vite@bca91c8 の反映です
> docs(static-deploy): bump version of actions/checkout and actions/upl

- config/shared-options.md
resolve #1145
vitejs/vite@e4c801c の反映です
> feat(define): handle replacement with esbuild

- config/server-options.md
resolve #1149
vitejs/vite@9866be0 の反映です
> docs: remove boolean from `server.https`

- guide/env-and-mode.md
resolve #1152
vitejs/vite@6e5e9b5 の反映です
> docs: update stale `define` docs

- _data/team.js
resolves #1186
Cherry picked from https://github.com/vitejs/vite/commit/63d7b7ffcd13a14d06729239e72c92342886d708
> docs: add mastodon link to sapphi-red (#1186)

- _data/team.js
resolves #1190
Cherry picked from https://github.com/vitejs/vite/commit/49d9c52fb80e1106d6124b4afa9081d610590bf4
> docs: Shinigami92 from X to Mastodon (#1190)

- guide/features.md
resolve #1148 
vitejs/vite@7234021 の反映です
> refactor(esbuild)!: remove esbuild 0.17 -> 0.18 compat

- config/index.md
- guide/api-javascript.md
resolve #1157 
vitejs/vite@d195860 の反映です
> feat!: add isPreview to ConfigEnv and resolveConfig

- guide/static-deploy.md
resolve #1162 
vitejs/vite@461f6c4 の反映です
> docs: add Kinsta deployment guide

- guide/migration.md
resolve #1163 
vitejs/vite@fc24b07 の反映です
> docs: add #14834 to migration guide

- guide/env-and-mode.md
resolve #1166
vitejs/vite@cd9e3e1 の反映です
> docs: add note about complex env based replacement

- .vitepress/theme/components/AsideSponsors.vue
- index.md
resolve #1200
vitejs/vite@dc58222 の反映です
> docs: add back link to ViteConf replay

- .vitepress/theme/styles/vars.css
resolves #1205
Cherry picked from https://github.com/vitejs/vite/commit/c61c376e605fb22817108800f94c700963200698
> docs: adjust sponsor logo (#1205)

- releases.md
resolve #1211
vitejs/vite@c936fb7 の反映です
> docs: remove Vite 5 feedback discussion note

- .vitepress/config.ts
- config/server-options.md
- guide/performance.md
resolve #1140
resolve #1154
resolve #1188
resolve #1203
> docs: add performance page

- .vitepress/config.ts
- .vitepress/theme/components/BlogIndex.vue
- .vitepress/theme/components/blog.data.ts
- .vitepress/theme/index.ts
- blog.md
- blog/announcing-vite2.md
- blog/announcing-vite3.md
- blog/announcing-vite4-3.md
- blog/announcing-vite4.md
- blog/announcing-vite5.md
> docs: add blog index page

- .vitepress/config.ts
resolve #1189
vitejs/vite@2004caa の反映です
> docs: add v4.vitejs.dev link to nav bar

- config/server-options.md
- guide/ssr.md
resolve #1169
vitejs/vite@e49ef02 の反映です
> docs(ssr): properly handle vite.middlewares after restart

- guide/features.md
resolve #1174 
vitejs/vite@2f39547 の反映です
> docs: note skipLibCheck

- guide/env-and-mode.md
resolve #1202 
vitejs/vite@79f79b4 の反映です
> docs: explain node_env and modes

- guide/api-javascript.md
resolve #1207 
vitejs/vite@e0c86d4 の反映です
> feat: allow providing parent httpServer on middleware mode

- guide/dep-pre-bundling.md
- guide/index.md
resolve #1210
vitejs/vite@918dd6d の反映です
> docs: dev vs build target

- guide/migration.md
- guide/troubleshooting.md
resolve #1216
vitejs/vite@d9ae680 の反映です
> docs(troubleshooting): note config mts extension

- config/shared-options.md
resolve #1221
vitejs/vite@d0b2153 の反映です
> fix: update type CSSModulesOptions interface

- guide/api-javascript.md
resolve #1223
vitejs/vite@cc980fe の反映です
> docs: indirect use vite.middlewares in example

- guide/migration.md
resolve #1224
vitejs/vite@78b34e0 の反映です
> docs: add a note about `moduleResolution` for rollup 4

- .vitepress/theme/index.ts
resolves #1246
Cherry picked from https://github.com/vitejs/vite/commit/9279c73c5fae9a9ce1fe4b3c714031d6646c6a97
> chore: remove no longer needed vitepress style fix (#1246)

- .vitepress/buildEnd.config.ts
- .vitepress/config.ts
- blog/announcing-vite2.md
- blog/announcing-vite3.md
- blog/announcing-vite4-3.md
- blog/announcing-vite4.md
- blog/announcing-vite5.md
- package.json
- yarn.lock
resolve #1225
vitejs/vite@dc494ad の反映です
> docs: add blog rss feed on docs build

- .vitepress/config.ts
resolve #1238 
vitejs/vite@7037070 の反映です
> docs: verify Mastodon account

- guide/index.md
resolve #1232 
vitejs/vite@339b20c の反映です
> docs: improve community templates section

- guide/migration.md
resolve #1233 
vitejs/vite@26a613a の反映です
> docs: reflect changes to manifest.json in migration.md

- guide/env-and-mode.md
resolve #1251
https://github.com/vitejs/vite/commit/5efbaadf4fa6cfc66cf47b51bcd21569d2f20659 の反映です。
> docs(env): add .env parsing note and vite-env.d.ts augmentation

- guide/features.md
1箇所typoを見つけたので、その修正です。
原文のリンク: https://github.com/vitejs/vite/blob/19e3c9a8a16847486fbad8a8cd48fc771b1538bb/docs/guide/features.md?plain=1#L68
> Add missing double-quote

- config/server-options.md
- guide/api-javascript.md
- guide/ssr.md
resolve #1234
resolve #1263
https://github.com/vitejs/vite/commit/9474c4be279e342db2264fa9e7a8b84abb54a93e と https://github.com/vitejs/vite/commit/56ae92c33cba6c86ab5819877c19b9ea39f7121b の反映です。
> feat: preserve vite.middlewares connect instance after restarts

- guide/features.md
resolve #1266
https://github.com/vitejs/vite/commit/953e697ea43c4aad6f728d0c44f8eb74b8218d41 の反映です。
> feat(glob-import): deprecate as option

- config/dep-optimization-options.md
resolve #1276
https://github.com/vitejs/vite/commit/757844f0bd7e52a160cf3f0afe241c03d7414921 の反映です。
> refactor: remove build time pre-bundling

- config/build-options.md
resolve #1283
vitejs/vite@53452df の反映です
> docs: `build.minify` defaults to `false` for SSR

- guide/index.md
resolve #1284
vitejs/vite@f3c11bb の反映です
> docs: changed bunx create-vite to bun create vite

- config/server-options.md
resolve #1289
https://github.com/vitejs/vite/commit/734a9e3a4b9a0824a5ba4a5420f9e1176ce74093 の反映です。
preview: https://deploy-preview-1297--vitejs-docs-ja.netlify.app/config/server-options.html#server-proxy
> docs: update proxy option link

- .vitepress/config.ts
- guide/api-vite-runtime.md
- guide/ssr.md
resolve #1293
https://github.com/vitejs/vite/commit/8b3ab0771842bda44129148c07739ebd86bdd62f の反映です。
少し長めですがよろしくお願いします。
Preview: https://deploy-preview-1295--vitejs-docs-ja.netlify.app/guide/api-vite-runtime.html
> feat: experimental Vite Runtime API 

- guide/features.md
> JSX サポート部分の訳を修正

- guide/api-javascript.md
resolve #1301
https://github.com/vitejs/vite/commit/37382d1f5764a4ccb9aaae8bf9e499e037d210fb の反映です。
> docs(api-javascript): update transformIndexHtml types

- guide/cli.md
resolve #1310 ←（`1000` の部分を実際の issue 番号に書き換えてください）
https://github.com/vitejs/vite/commit/f1a42429e1d24230a4a78cca82657e2d3602a7b2 の反映です
preview:
https://deploy-preview-1316--vitejs-docs-ja.netlify.app/guide/cli.html#%E3%82%AA%E3%83%95%E3%82%9A%E3%82%B7%E3%83%A7%E3%83%B3-1
> refactor: remove vite build --force

- config/dep-optimization-options.md
fix #1318
fix #1319
fix #1320
#1319 と #1320 は、単純に #1318 のlint errorの修正なので合わせて直しました。
> docs: improve optimizeDeps.esbuildOptions type

- .vitepress/config.ts
resolve #1323 
vitejs/vite@65ef383 の反映です
> docs: remove vite rollup plugins from resources

- guide/api-plugin.md
- guide/using-plugins.md
resolve #1324
vitejs/vite@296ce24 の反映です
> docs: remove links to vite-rollup-plugins

- _data/team.js
resolves #1330
Cherry picked from https://github.com/vitejs/vite/commit/b3f557deee57625fcaf5049b3ddad061946071b9
> docs: complete team social links (#1330)

- guide/ssr.md
resolve #1327
https://github.com/vitejs/vite/commit/63a39c244b08cf1f2299bc2c3cfddcb82070d05b の反映です。
`experimental` の1語が追加されただけです。
> refactor(runtime): minor tweaks

- _data/team.js
resolves #1335
Cherry picked from https://github.com/vitejs/vite/commit/e30fac434f3cd1b33c5b48dd090bf010773e3ec5
> chore: review team members (#1335)

- .vitepress/config.ts
resolves #1337
Cherry picked from https://github.com/vitejs/vite/commit/cc388d9c84e44a9b7d990dfbd3023aaf20494ecd
> docs: add canonical url in head (#1337)

- config/server-options.md
resolve #1342
https://github.com/vitejs/vite/commit/ee562070f2a46d8f71eac117333e950737e04bf1 の反映です。
> docs(hmr): document `hmr.protocol` setting

- guide/performance.md
resolve #1346
vitejs/vite@e92abe5 の反映です
> docs: add reference link for set debug environment variable on Windows

- guide/static-deploy.md
resolve #1348
https://github.com/vitejs/vite/commit/8c0306078a4614954ed7ab60d378b4659657b585 の反映です。
> docs(static-deploy): update workflow

- guide/performance.md
resolve #1350
https://github.com/vitejs/vite/commit/2fc252e873ed06077a4f67c8114a5853f7a90641 の反映です。
> docs: replace `DEBUG="vite:foo"` with `--debug foo`

- guide/api-javascript.md
resolve #1364
https://github.com/vitejs/vite/commit/98888439e07c1dc6425deea3474330ad27b8bf33 の反映です。
> feat: formalize waitForRequestsIdle (experimental)

- guide/build.md
resolve #1361
https://github.com/vitejs/vite/commit/5aabad32b276ebc7940a8ce415243f5b526613db の反映です。
> fix(docs): fix load error handling window reload example

- config/shared-options.md
- guide/features.md
resolve #1360
https://github.com/vitejs/vite/commit/1d5eec477e5f1951e024e2105fd4a7ad536cb48b の反映です。
> feat: csp nonce support

- .vitepress/config.ts
- .vitepress/theme/index.ts
- .vitepress/tsconfig.json
- config/build-options.md
- config/dep-optimization-options.md
- config/index.md
- config/server-options.md
- config/shared-options.md
- guide/api-hmr.md
- guide/api-javascript.md
- guide/api-plugin.md
- guide/assets.md
- guide/backend-integration.md
- guide/build.md
- guide/dep-pre-bundling.md
- guide/features.md
- guide/ssr.md
- guide/using-plugins.md
- package.json
- pnpm-lock.yaml
resolve #1366
resolve #1371
https://github.com/vitejs/vite/commit/6f8a3206653127a1ca9e20880af117d3a7c4fadc の反映です。
#1366 で元リポジトリにも `docs/package.json` の追加が行われていました。
https://github.com/vitejs/vite/commit/6f8a3206653127a1ca9e20880af117d3a7c4fadc#diff-adfa337ce44dc2902621da20152a048dac41878cf3716dfc4cc56d03aa212a56
日本語版用の `package.json` に #1371 と合わせて更新を反映してみましたが、問題ないか確認してもらえると嬉しいです。
> docs: add `@shikiji/vitepress-twoslash`

- guide/api-plugin.md
resolve #1374 
vitejs/vite@3a73e48 の反映です
> docs: clarify enforce vs hook.order

- config/shared-options.md
resolve #1380
vitejs/vite@e14123f の反映です
> docs(css): duplicate `@import` behavior

- guide/build.md
resolve #1381 
vitejs/vite@45a06da の反映です
> chore: deprecate splitVendorChunkPlugin

- guide/backend-integration.md
resolve #1384
vitejs/vite@f1e67b6 の反映です
> docs: fix capitalization typos

- package.json
- pnpm-lock.yaml
resolve #1387 
vitejs/vite@a78e265 の反映です
> chore(deps): update all non-major dependencies

- config/dep-optimization-options.md
resolve #1393
https://github.com/vitejs/vite/commit/f8e0791e3f7c7c39c041a563e77396eca706d05e の反映です。
Preview: https://deploy-preview-1396--vitejs-docs-ja.netlify.app/config/dep-optimization-options.html#optimizedeps-entries
> docs: update dep optimization options entries

- guide/api-vite-runtime.md
- guide/ssr.md
resolve #1394 
vitejs/vite@e526573 の反映です
> docs: add links to environment api

- .vitepress/theme/components/AsideSponsors.vue
- index.md
resolve #1397 
vitejs/vite@6c323d5 の反映です
> docs: SF meetup promo

- guide/features.md
resolve #1400
https://github.com/vitejs/vite/commit/8e54bbd74d86537b449641a6623b1bc3800e82b2 の反映です。
> feat: write cspNonce to style tags

- guide/static-deploy.md
resolve #1408 
vitejs/vite@72343be の反映です
> docs(static-deploy): add xmit deployment guide

- guide/static-deploy.md
resolve #1409
vitejs/vite@2f42006 の反映です
> docs(static-deploy): add criteria comment

- guide/backend-integration.md
resolve #1415
https://github.com/vitejs/vite/commit/7a8ae49deb5e63d47dbc7a3ef24d0c6404184e0a の反映です。
> docs: update manifest example

- guide/api-hmr.md
- guide/api-plugin.md
resolve #1414
https://github.com/vitejs/vite/commit/66f12ab40b38972f9a9837e485c85d144385ffa4 の反映です。
> docs: add custom event types docs

- .vitepress/config.ts
resolves #1426
Cherry picked from https://github.com/vitejs/vite/commit/31f526f63830cad46a0a518e89011eb01de4cbc9
> docs: add meta `og:site_name` & update `og:title` (#1426)

- guide/api-plugin.md
resolve #1430
https://github.com/vitejs/vite/commit/e7d38ab1c45b9d17f182f89d0c129932e2f994eb の反映です。
> docs: deprecate server.hot

- guide/index.md
resolve #1432
https://github.com/vitejs/vite/commit/4053c6f632d462280aa7c3ced2def8cc0cc42dd9 の反映です。
> docs: add comment in create project guide

- .vitepress/buildEnd.config.ts
- .vitepress/config.ts
- .vitepress/theme/composables/sponsor.ts
resolve https://github.com/vitejs/docs-ja/issues/1436
https://github.com/vitejs/vite/commit/8f167653ede5d61f9d08ffa86c91e218557199ae の反映です。
> chore: move to eslint flat config

- guide/env-and-mode.md
resolve #1459
https://github.com/vitejs/vite/commit/8eecc62a9041440baf3b828a36a2f2a4e43c191a の反映です。
> docs(env-and-mode): fix typescript lib links (fix #17488)

- guide/migration.md
resolve #1473
https://github.com/vitejs/vite/commit/1b0979f44c7ffa4e7dfd1488c3939f45f4206efe の反映です。
> docs(migration): fix wrong import

- config/preview-options.md
resolve #1478
https://github.com/vitejs/vite/commit/14e14726d11ac55c37cc2d15aaf935be18ef925b の反映です。
> docs(config): update `preview.https` type

- _data/team.js
resolves #1484
Cherry picked from https://github.com/vitejs/vite/commit/167006e74751a66776f4f48316262449b19bf186
> chore: move shinigami to team emeriti (#1484)

- config/index.md
resolve #1488
https://github.com/vitejs/vite/commit/e1fb0fa27097566c8fa5e792f965c29fc050b837 の反映です。
> docs: show usage with `satisfies` operator

- .vitepress/theme/components/AsideSponsors.vue
- index.md
resolve #1490
https://github.com/vitejs/vite/commit/63fabfc26dc9884772d5576888992b6e798d8a35 の反映です。
> docs: link to ViteConf 24

- _data/team.js
resolves #1493
Cherry picked from https://github.com/vitejs/vite/commit/6e971367f77b63836673395fcd4b3a9d2ed0bde8
> docs: move soda to team emiriti (#1493)

- guide/comparisons.md
resolve #1492
https://github.com/vitejs/vite/commit/8e1abe5be6e645d781c6a01a171729465e659b5f の反映です。
> docs: update comparisons.md with correct information about WMR

- _data/team.js
resolve #1495
https://github.com/vitejs/vite/commit/2c4ef1137641eb797ce32eb7a2238eddd13dddd5 の反映です。
> chore: add hiroshi to team

- guide/index.md
resolve #1502
https://github.com/vitejs/vite/commit/d81de4878ab65eede965b4353c26d8c727c9e164 の反映です。
preview: https://deploy-preview-1503--vitejs-docs-ja.netlify.app/guide/#%E6%9C%80%E5%88%9D%E3%81%AE-vite-%E3%83%95%E3%82%9A%E3%83%AD%E3%82%B7%E3%82%99%E3%82%A7%E3%82%AF%E3%83%88%E3%82%92%E7%94%9F%E6%88%90%E3%81%99%E3%82%8B
> docs: improve additional command line options by code-group

- config/shared-options.md
resolve #1508
https://github.com/vitejs/vite/commit/73a3de01d2baaeefeabfa46c28fb49550643b23a の反映です。
> feat(css): support sass modern api

- config/server-options.md
resolve #1514
https://github.com/vitejs/vite/commit/4de659c351589b83a83a7a42f3da5b071a625662 の反映です。
> fix: opt-in server.fs.cachedChecks

- guide/api-plugin.md
resolve #1524
https://github.com/vitejs/vite/commit/d78d44bc314b9ef3c1f2fae2775b131da6580980 の反映です。
> docs: reload after invalidate

- guide/index.md
resolve #1541
https://github.com/vitejs/vite/commit/2adc5aaae4f57c08b42864b3bf899e9b10564189 の反映です。
> docs: edit Manual Install instructions on docs guide page

- changes/hotupdate-hook.md
- changes/index.md
- changes/per-environment-apis.md
- changes/shared-plugins-during-build.md
- changes/ssr-using-modulerunner.md
- changes/this-environment-in-hooks.md
> Breaking Changes

- .vitepress/config.ts
resolves #1556
Cherry picked from https://github.com/vitejs/vite/commit/a34a73a3ad8feeacc98632c0f4c643b6820bbfda
> docs: use search-only key (#1556)

- guide/api-environment.md
resolve #1566
vitejs/vite@9470011 の反映です
> fix: require serialization for HMRConnection.send on implementation side

- guide/api-environment.md
resolve #1567 
vitejs/vite@fb292f2 の反映です
> feat: introduce RunnableDevEnvironment

- .vitepress/theme/components/landing/3. frameworks-section/FrameworksSection.vue
resolves #1577
Cherry picked from https://github.com/vitejs/vite/commit/51bb1680891d87b9a5372ee0e5372a9a75e0674a
> docs(landing): update Qwik url (#1577)

- .vitepress/theme/components/landing/3. frameworks-section/FrameworksSection.vue
- .vitepress/theme/components/landing/3. frameworks-section/images/preact.svg
resolve #1580
https://github.com/vitejs/vite/commit/ad4f4048e295cc2e3bdc338f5514bac8584fab30 の反映です。
> docs: add Preact logo

- .vitepress/theme/components/landing/5. sponsor-section/SponsorSection.vue
resolves #1592
Cherry picked from https://github.com/vitejs/vite/commit/f721677d8c2b4559f7eb47e0aa4921a3c66f52f1
> chore(docs): add margin to h4 (#1592)

- config/dep-optimization-options.md
resolve #1594 
vitejs/vite@0eda2ea の反映です
> docs: update EsbuildBuildOptions link

- .vitepress/theme/components/landing/2. feature-section/FeatureTypedAPI.vue
resolves #1598
Cherry picked from https://github.com/vitejs/vite/commit/41735a72a3b0b1f8b058a4d58b5f556b420fa756
> chore: docs style (#1598)

- guide/api-environment.md
resolve #1600 
vitejs/vite@cd368f9 の反映です
> refactor: rename runner.destroy() to runner.close()

- guide/build.md
resolve #1609
https://github.com/vitejs/vite/commit/7db105daaf5a128edd66b7aa9b0ae0fdb83a30be の反映です。
> docs: relative base path

- config/server-options.md
resolve #1628
https://github.com/vitejs/vite/commit/105ca12b34e466dc9de838643954a873ac1ce804 の反映です。
> feat: add .git to deny list by default

- .vitepress/config.ts
resolves #1632
Cherry picked from https://github.com/vitejs/vite/commit/257883fccc36f27cc879af249eeba353ebe94cdd
> docs: reload due to gsap and shiki (#1632)

- guide/backend-integration.md
resolve #1630
vitejs/vite@964a618 の反映です
> docs(backend-integration): add an example `importedChunks`

- guide/assets.md
resolve #1627
https://github.com/vitejs/vite/commit/159b4f4d9ee24d367f574ee0e563f5ced07c169d の反映です
> docs: change docs to include more details about public directory

- config/shared-options.md
resolve #1645
https://github.com/vitejs/vite/commit/b80daa7c0970645dca569d572892648f66c6799c の反映です
> feat(json)!: add `json.stringify: 'auto'` and make that the default

- guide/backend-integration.md
resolve #1654
https://github.com/vitejs/vite/commit/c148676c90dc4823bc6bdeb8ba1e36386c5d9654 の反映です。
> fix(manifest): non entry CSS chunk src was wrong

- .vitepress/config.ts
- guide/api-environment.md
resolve #1661
https://github.com/vitejs/vite/commit/1ac22de41cf5a8647847070eadeac3231c94c3ed の反映です。
> refactor: optimizeDeps back to top level

- guide/api-environment.md
resolve #1664 
vitejs/vite@915cd7f の反映です
> docs: top-level client environment config

- config/server-options.md
- guide/api-javascript.md
resolve #1668
https://github.com/vitejs/vite/commit/192d555f88bba7576e8a40cc027e8a11e006079c の反映です。
> feat!: update to chokidar v4

- .vitepress/theme/styles/landing.css
resolves #1679
Cherry picked from https://github.com/vitejs/vite/commit/887ce8bc9a04e4f99be8d02630f2077ea3fc54c9
> docs: optimize home page styles (#1679)

- guide/migration.md
resolve #1674
vitejs/vite@3a46f97 の反映です
> docs: migration guide for #18070

- _data/team.js
> docs: add bluesky profiles

- guide/ssr.md
resolve #1701
https://github.com/vitejs/vite/commit/ce0eec91c9b5a91c52bf5b9bae6173d35f6e1649 の反映です。
> chore: upgrade to express 5

- config/index.md
resolve #1697 
vitejs/vite@b2fa726 の反映です
> docs(config): remove unused argument command

- guide/features.md
resolve #1716
https://github.com/vitejs/vite/commit/59249cf2fdd7ecec525d237455e0d28d272c1d28 の反映です。
> docs: fix attribute in example

- .vitepress/theme/styles/landing.css
resolves #1718
Cherry picked from https://github.com/vitejs/vite/commit/f83ba1e29e1a77fbf88c655cab249f15e497acfe
> docs: fix mobile menu background on light mode landing page (#1718)

- guide/ssr.md
resolve #1721
https://github.com/vitejs/vite/commit/584a573e1fdfa64018b2c56d147f2b4fec2d9733 の反映です。
> docs: note about a silly edge case in the ssr guide

- config/ssr-options.md
resolve #1720
https://github.com/vitejs/vite/commit/f39896e7ffb1a00cb3cf8237221f2908bd50a758 の反映です。
> docs: expand description of `externalConditions`

- config/shared-options.md
- config/ssr-options.md
- guide/migration.md
resolve #1728
vitejs/vite@c12c653 の反映です
> feat: expose default mainFields/conditions

- .vitepress/theme/components/landing/4. community-section/CommunitySection.vue
resolves #1740
Cherry picked from https://github.com/vitejs/vite/commit/a3a4400c6b32bae02b7c621e8275c088d995f700
> docs: update @cpojer avatar on the landing page (#1740)

- .vitepress/tsconfig.json
- guide/performance.md
resolve #1754
https://github.com/vitejs/vite/commit/b0fc6e3c2591a30360d3714263cf7cc0e2acbfdf の反映です。
> revert: update moduleResolution value casing

- guide/assets.md
resolve #1763
https://github.com/vitejs/vite/commit/3ffcb183449efcc2aa1cf22d945945a0e94ce7ed の反映です
> docs(assets): update static asset URL transformation in dev

- plugins/index.md
resolve #1764
https://github.com/vitejs/vite/commit/44a0f40b36a11e91dbcff518a08c3d77218576f5 の反映です
> docs: correct docs about plugin-react-swc

- _data/team.js
resolves #1778
Cherry picked from https://github.com/vitejs/vite/commit/f97ce60d7a420d4d1ccc1c6caf79fcae32ff87f7
> docs: add profile card (#1778)

- config/index.md
resolve #1785 
https://github.com/vitejs/vite/commit/ccd1a4c4145ee1069d7baea56981a0322e7be864 の反映です。
> docs: display file name in a better way 

- .vitepress/config.ts
resolves #1793
Cherry picked from https://github.com/vitejs/vite/commit/e1b520c4fbb3d65a06b04ce8fb3acfa71f253ee9
> docs: fix canonical links (#1793)

- guide/ssr.md
resolve #1804 
https://github.com/vitejs/vite/commit/080266213288ea2bb2c8061865ec47dc287081b0 の反映です
> docs(ssr): remove link to Discord channel

- guide/api-environment-frameworks.md
- guide/build.md
resolve #1806
https://github.com/vitejs/vite/commit/4f5845a3182fc950eb9cd76d7161698383113b18 の反映です。
> docs: unify `__dirname` usage

- config/preview-options.md
resolve #1814
https://github.com/vitejs/vite/commit/c9a4b7a0d87fab05ff2ff12cfc2013bd575f57ff の反映です
> docs: fix preview.cors description

- guide/build.md
- guide/index.md
resolve #1826
https://github.com/vitejs/vite/commit/97569efd9d26b5c24d3a702d3171426f97c403cc の反映です。
> docs: rephrase browser range and features relation

- guide/troubleshooting.md
resolve #1840 
https://github.com/vitejs/vite/commit/b0457b4173ee7f3781b4a12e462f6c1717de7ad1 の反映です
> docs: add troubleshooting section for path with `*`

- guide/assets.md
resolve #1844
https://github.com/vitejs/vite/commit/84e6d6044863e3e620addcf9065010b30a860e22 の反映です
> docs: fix dead link to houdini.how

- guide/index.md
resolve #1862
https://github.com/vitejs/vite/commit/a464971716114c1ce06e195f0d7d41771b2ed295 の反映です。
> docs: mention pkg.pr.new for unreleased commits

- .vitepress/theme/composables/sponsor.ts
- _data/team.js
resolves #1867
Cherry picked from https://github.com/vitejs/vite/commit/00deea4ff88e30e299cb40a801b5dc0205ac913d
> docs(team): update bluwy bio (#1867)

- config/index.md
resolve #1877
https://github.com/vitejs/vite/commit/96ee4f116deac72dc8c236ef904116c3022f6b72 の反映です。
> docs: add vscode debug error situation description

- public/_redirects
resolves #1898
Cherry picked from https://github.com/vitejs/vite/commit/9ae58f2aa2c7299b847a4f6f5c83c14bb2a1f347
> docs: make redirects permanent (#1898)

- guide/rolldown.md
resolve #1906
https://github.com/vitejs/vite/commit/05beb9cb780ae982aa5d6e675e1604625fb32b81 の反映です
> docs: plugin authors guide for rolldown-vite

- .vitepress/config.ts
- package.json
- pnpm-lock.yaml
- public/_redirects
resolve #1910 
https://github.com/vitejs/vite/commit/541dff1ed5ea411f7970b3d04d2d28c8f172d832 の反映です（とりいそぎ英語のまま適用）
> docs: generate llms.txt

- guide/rolldown.md
resolve #1916
https://github.com/vitejs/vite/commit/7c26d090442de3d1b13520fb4c7bc2a85c05e826 の反映です。
> docs: add rolldown video

- guide/rolldown.md
resolve #1922 
https://github.com/vitejs/vite/commit/f65a8165d13a3a26da14b12f38f1b4cda32c72e2 の反映です
> docs(rolldown): mention aliasing

- guide/rolldown.md
resolve #1930
https://github.com/vitejs/vite/commit/3db608a4c30a327d05007a4128b178493b1f4691 の反映です
> docs(rolldown): make clear changes should be applied in `package.json`

- guide/api-environment-frameworks.md
resolve #1932
https://github.com/vitejs/vite/commit/b5f70dda08a4b87059f3e5f5e0de823270018a1a の反映です。
> docs: fix example in api-environment-frameworks.md

- guide/ssr.md
- package.json
- pnpm-lock.yaml
resolve #1935
https://github.com/vitejs/vite/commit/123fbae4d63dcfbb87e0f4b6d42727b234a947b2 の反映です
> docs: update to express 5

- config/server-options.md
resolve #1939 
https://github.com/vitejs/vite/commit/c22c43de612eebb6c182dd67850c24e4fab8cacb の反映です
> fix: check static serve file inside sirv

- .vitepress/config.ts
resolves #1945
Cherry picked from https://github.com/vitejs/vite/commit/f32d1746c5c467791ccc7929f9782df764c5c26f
> docs(i18n): add Persian language docs link (#1945)

- guide/api-environment-frameworks.md
resolve #1951 resolve #1956
https://github.com/vitejs/vite/commit/5da659de902f0a2d6d8beefbf269128383b63887, https://github.com/vitejs/vite/commit/94cd0f9583c550db0672aeca346a34a4677e3446 の反映です
> feat: buildApp hook

- .vitepress/theme/components/AsideSponsors.vue
- .vitepress/theme/components/YouTubeVideo.vue
- .vitepress/theme/components/landing/1. hero-section/HeroDiagram.vue
- .vitepress/theme/components/landing/1. hero-section/HeroSection.vue
- .vitepress/theme/components/landing/2. feature-section/FeatureCI.vue
- .vitepress/theme/components/landing/2. feature-section/FeatureFlexiblePlugins.vue
- .vitepress/theme/components/landing/2. feature-section/FeatureInstantServerStart.vue
- .vitepress/theme/components/landing/2. feature-section/FeatureOptimizedBuild.vue
- .vitepress/theme/components/landing/2. feature-section/FeatureRichFeatures.vue
- .vitepress/theme/components/landing/2. feature-section/FeatureSection.vue
- .vitepress/theme/components/landing/3. frameworks-section/FrameworksSection.vue
- .vitepress/theme/components/landing/4. community-section/CommunitySection.vue
- .vitepress/theme/components/landing/5. sponsor-section/SponsorSection.vue
- .vitepress/theme/components/landing/common/SvgNode.vue
- .vitepress/theme/composables/sponsor.ts
- .vitepress/theme/composables/useCardAnimation.ts
- .vitepress/vite-env.d.ts
resolve #1965 
https://github.com/vitejs/vite/commit/1a660a9f48ec7a0a3561d3254d62c3d7d8bca775 の反映です
> docs: refactor components to TypeScript

- guide/features.md
resolve #1973 
https://github.com/vitejs/vite/commit/e7d6f8111a6c32eab74778c73552023660e0c75a の反映です
> docs(features): mention inlining in static assets section

- config/dep-optimization-options.md
resolve #1981
https://github.com/vitejs/vite/commit/6d2dcb494db9f40565f11b50bdbb8c1b7245697d の反映です。
> feat: stabilize `optimizeDeps.noDiscovery`

- config/shared-options.md
- guide/api-hmr.md
- guide/features.md
resolve #1988
https://github.com/vitejs/vite/commit/3093bd1e5654bd77814fe1286a144cdf8522d23d の反映です
> docs: remove `env.d.ts` mentions

- guide/index.md
resolve #1989
https://github.com/vitejs/vite/commit/aec0770eb35960e1946e7e397e98827453551a2f の反映です
> docs: clarify dev browser support version

- guide/api-environment-plugins.md
resolve #2005 
https://github.com/vitejs/vite/commit/a330b805b0733fadd1f7d586218c2aafcbb41a7f の反映です
> fix: applyToEnvironment after configResolved

- guide/features.md
resolve #2013
https://github.com/vitejs/vite/commit/bdb6de5f0aab581245cb0bd10b3e6f5af72cb861 の反映です。
> docs: update @vitejs/plugin-react-swc link in features.md

- guide/api-environment-plugins.md
resolve #2032
https://github.com/vitejs/vite/commit/535d4fee45bd7d93d587f8779e6238de141064e7 の反映です
> docs: per-environment state in plugins

- .vitepress/config.ts
- guide/index.md
- netlify.toml
- package.json
- pnpm-lock.yaml
resolve #2035 
https://github.com/vitejs/vite/commit/6f51997bb9285ea8c7de1c3f8e36acc72bb9151a の反映です
> docs(deps): update to vitepress v2 alpha

- guide/rolldown.md
resolve #2047 
https://github.com/vitejs/vite/commit/bab4fbc42bc0f5f98071588e8411c802b630feb3 の反映です
> docs(rolldown): update manualChunks status

- guide/dep-pre-bundling.md
resolve #2051 
https://github.com/vitejs/vite/commit/217c6be0be1d61782ec8a77ed0b2a691ea2e6de0 の反映です
> docs: mention `bun.lock` for lockfile

- guide/rolldown.md
resolve #2055
https://github.com/vitejs/vite/commit/81a406672b64dcdaf3b9d3def21c82e50a4fc0d0 の反映です。
> docs: fix regular expression on the Rolldown page

- .vitepress/config.ts
- .vitepress/inlined-scripts/banner.js
- .vitepress/theme/components/SponsorBanner.vue
- .vitepress/theme/index.ts
resolve #2064
https://github.com/vitejs/vite/commit/27a192fc95036dbdb6e615a4201b858eb64aa075 の反映です
> docs: add viteconf2025 banner

- changes/per-environment-apis.md
resolve #2070
https://github.com/vitejs/vite/commit/c1279e75401ac6ea1d0678da88414a76ff36b6fe の反映です
> feat: add `removeServerPluginContainer` future deprecation

- changes/per-environment-apis.md
resolve #2073
https://github.com/vitejs/vite/commit/6970d1740cebd56af696abf60f30adb0c060f578 の反映です
> feat: add `removeServerReloadModule` future deprecation

- .vitepress/config.ts
- guide/api-plugin.md
- package.json
- pnpm-lock.yaml
resolve #2086
https://github.com/vitejs/vite/commit/8979b143bb31eacc21bc77605506c2151649bb1e の反映です
> docs: add `markdown-it-image-size` to reduce layout shift

- guide/index.md
resolve #2094
https://github.com/vitejs/vite/commit/73b052ec0f6e6ba1f00659828dfbab3a59d7d1d0 の反映です
> docs: rework scaffolding your first vite project

- guide/backend-integration.md
resolve #2099
https://github.com/vitejs/vite/commit/bd1e01997d938e03461125679deccf3ecc60b60f の反映です
> docs: improve manifest.json documentation clarity and completeness

- guide/api-plugin.md
- guide/features.md
resolve #2128
https://github.com/vitejs/vite/commit/d52cf887fddcfe9e19b02d20de302fae4bbffd1f の反映です
> docs: use root relative paths for internal links

- config/preview-options.md
resolve #2141
https://github.com/vitejs/vite/commit/91b5dc18e7119d0df59abfdaa6126e9f58503c65 の反映です
> docs(config): fix type of preview.allowedHosts to 'string[] | true'

- guide/static-deploy.md
resolve #2153
https://github.com/vitejs/vite/commit/6d3e37158bc2b9447621140f6329142317f19877 の反映です
> docs: add zephyr cloud deployment docs

- .github/workflows/lint.yml
- guide/static-deploy-github-pages.yaml
resolve #2159
https://github.com/vitejs/vite/commit/8ccf2b671f1fa8fea5c342158e90af56e5ae3980 の反映です
> chore(deps): update actions/setup-node action to v5

- guide/api-plugin.md
- guide/rolldown.md
resolve #2172
https://github.com/vitejs/vite/commit/d395e821d9927875cca9fb7d7354478b2701f8c7 の反映です
> docs: add plugin hook filter info to Plugin Authors guide
