blog/announcing-vite2.md, guide/features.md, guide/index.md
=> 旧190 chore: move from @vitejs/create-app to create-vite #19

config/index.md, guide/env-and-mode.md
resolves #98 
vitejs/vite@dfdb9cc の対応です
差分取り込み https://github.com/vitejs/docs-ja/commit/46bbf3f16d65fd2c310667db831283edbb690c1a と翻訳 https://github.com/vitejs/docs-ja/commit/954b83838ef4053d53df86a3f3b8bafe658a4284 でコミット分けてます
---
resolves #103 
vitejs/vite@74af8c4 も含めました
（リンク URL `envPrefix` → `envprefix`）
=> apply vitejs/vite@dfdb9cc

guide/api-hmr.md
resolves #172 
vitejs/vite@12ee156 の適用
=> docs: add missing `prune` api in HMR

config/index.md
resolves #175 
vitejs/vite@1a15460 の適用と翻訳
ドキュメントの変更は1ファイルのみ
=>         feat: `server.fs.deny` support    

guide/api-plugin.md
resolves #189 
vitejs/vite@981e1f5 の適用と翻訳
=> docs: virtual modules ID naming convention

guide/migration.md
resolves #197 
vitejs/vite@211f183 の内、`migration.md` のみ対応
（`config/index.md` は #202 で対応）
=> chore(deps): massive major deps update

config/index.md
resolves #222 resolves #224
vitejs/vite@8a8b296 と vitejs/vite@c344865 の取り込みです
（`api-plugin.md` はすでに空行削除されていたので差分なし）
=> docs: css.modules.localsConvention is null by default

guide/static-deploy.md
resolves #226 
vitejs/vite@4bc9483 の取り込みです
=> docs: fix gitlab pages deploy syntax

guide/static-deploy.md
resolves #236 
vitejs/vite@ae3a443 のうち、ブランチ名変更の差分を反映
改行削除は #234 で対応
=> docs: use main branch instead of master

package.json
コミット時、全ての md ファイルを textlint でチェックしていて時間がかかるので、ステージングファイルのみ lint するよう変更しました
=> コミットするファイルだけを lint

config/index.md
resolves #255
vitejs/vite@0f393a1 の取り込みと翻訳です。
=> docs(lib-mode): add a caveat to the build.minify docs for 'es' format

config/index.md
resolves #280
vitejs/vite@678e0f2 の取り込みと翻訳です
=> docs(config): added an example about proxying websockets

blog/announcing-vite2.md, config/index.md, guide/api-javascript.md, guide/static-deploy.md
resolve #374
vitejs/vite@c296130 の反映です
- `CONTRIBUTING.md` は「日本語翻訳ガイド」に変わっているので修正なし
- `why.md` は（おそらく）翻訳時に対応済みなので修正なし
=> chore: fix term cases

config/index.md
resolve #395 
https://github.com/vitejs/vite/commit/6198911faeee3b915fc0d4ff24fbb918f3e1d558 の反映です
=> docs: import.meta.url is replaced even if ESM

config/index.md
resolve #411 
https://github.com/vitejs/vite/commit/b5c370941bb36bdb420433ca16cea9c2402b9810 の反映です。
また、ISSUEで確認させていただいた上、
`conifg/index.md`内にある行末のスペースも削除しています。
=> refactor: remove deprecated api for 3.0

config/index.md
resolve #369
vitejs/vite@93ae8e5 の反映です
=> fix: infer client port from page location

guide/build.md
resolve #325 resolve #335
https://github.com/vitejs/vite/commit/849e8456e1f7609040030c87cdc51e2fc76235b7, https://github.com/vitejs/vite/commit/7dcf370d0f27ef7d5073006fcd943ab9083cabe1 の取り込みと翻訳です
=> refactor: avoid splitting vendor chunk by default

guide/features.md
resolve #331
vitejs/vite@87ecce5 の取り込みと翻訳です
=> fix: deprecate { assert: { type: raw }} in favor of { as: raw }

guide/index.md
resolve #438 
https://github.com/vitejs/vite/commit/e23ba3593cf71edf76840b4f57935c575c698793 の反映です。
=> docs: correct link to Discord

config/index.md
resolve #366
vitejs/vite@4c95e99 の反映です
=> fix: optimizeDeps.entries default ignore paths

guide/features.md
#463 の一部の修正です
元コミット: https://github.com/vitejs/vite/commit/75c3bf65694bc89b395e03dabb81721871d24a9c
=> fix: wasmの訳の修正

config/build-options.md
resolve #488 
https://github.com/vitejs/vite/commit/164f528838f3a146c82d68992d38316b9214f9b8 の反映です。
本家の方にはpnpm-lock.yamlも変更があったのですが、
lockファイル内の記述的にplaygroundを動かすために必要と思われ、翻訳サイトにはなくて問題ないと判断し、ライブラリの変更は特にしてません。
=> refactor!: make terser an optional dependency

guide/migration.md
resolve #498 
https://github.com/vitejs/vite/commit/b4bddb92003e6e7cd7ad412d1ea09cbec08bb922#diff-93c9f7e5380e402192ad1543f70657fd5bc38cb2a6f05bdc1968bb4b6d7f40c9R115 の反映です。
=> docs: add some changes to "Migration from v2"

config/server-options.md
resolve #515
resolve #517
https://github.com/vitejs/vite/commit/4061ee02bfdc7a3264136e838623da27b428e7aa と https://github.com/vitejs/vite/commit/26ee6bfe3991b67f3452d85278a0874a782848d1 の反映です
=> fix: infer hmr ws target by client location

package.json, vite.config.ts, yarn.lock
resolve #557
https://github.com/vitejs/vite/commit/339d9e394620c843c9c0c9c8afc4d77e27879620 の反映です
また、vitepressのバージョンをviteに合わせて1.0.0-alpha.4にしています
https://github.com/vitejs/vite/blob/339d9e394620c843c9c0c9c8afc4d77e27879620/package.json#L93
https://github.com/vitejs/vite/blob/339d9e394620c843c9c0c9c8afc4d77e27879620/pnpm-lock.yaml#L8468
=> feat: avoid scanner during build and only optimize CJS in SSR, chore: update vitepress to 1.0.0-alpha.4

guide/migration.md
resolve #564
https://github.com/vitejs/vite/commit/26bcdc3186807bb6f3817119cd7e64ae8308a057 の反映です
=> feat: expose server resolved urls

guide/ssr.md
リンクが壊れていたので修正しました
https://github.com/vitejs/vite/commit/e5ddfa824656fe34d8bda8a440505be7adf67a1e の地点でも壊れていなかったので、おそらく原文は壊れていません
=> fix: SSRガイドのconfigureServerのリンク

.vitepress/config.ts
- Source repo should be updated to `vitejs/docs-ja`.
- `vitejs/vite` had all paths nested under `docs/` which is not needed here in this new repo. I have removed it.
=> "Edit page" GitHub link points to incorrect path

guide/build.md
resolve #742
vitejs/vite@3cc65d7 の反映です
=> feat!: support safari14 by default for wider ES2020 compatibility

blog/announcing-vite3.md
resolves #865
Cherry picked from https://github.com/vitejs/vite/commit/374b25e7ee4fe7091ae7575930cd9d99c4b74309
=> docs: fix migration guide link in vite v3 news (#865)

config/build-options.md
resolve #879
vitejs/vite@3551f75 の反映です
=> docs: build.assetsDir only used in non lib mode

.vitepress/config.ts
resolves #918
Cherry picked from https://github.com/vitejs/vite/commit/4a42c9093ec9d6ec8782bde3a2aafebc5f9f1d08
=> chore: add `português` to locales in `.vitepress/config.ts` (#918)

config/shared-options.md
resolve #911 
vitejs/vite@5968bec の反映です
=> feat(css): add preprocessor option to define stylus vars & funcs

guide/features.md
resolve #924
vitejs/vite@1a8af8d の反映です
=> docs(css): default and named imports from css files deprecated

guide/features.md
resolve #953
vitejs/vite@ef89ca6 の反映です
=> docs: correct glob import as example

guide/migration.md
軽微なtypoなのでissueなしです。
[環境変数](https://ja.vitejs.dev/guide/migration.html#%E7%92%B0%E5%A2%83%E5%A4%89%E6%95%B0)の項目で
> `` ` `` を含む値
の `` ` ``が表示されていなかったのを修正しています
=> fix:環境変数の項目のcode blockの修正

guide/api-plugin.md, guide/features.md, plugins/index.md
resolve #962
mainブランチにすでに #965 はマージされていると認識しているんですが、差分として表示されてしまっています。
原因を調査したのですがわかっておらず、ドラフトでPR出しています。
前回チェック項目が失敗しているのも少し気になっております。
=> docs: update Vue 2 plugins

guide/build.md
resolve: https://github.com/vitejs/docs-ja/issues/990
https://github.com/vitejs/vite/commit/17511e03c2d4d3ad8191101d1cf04c4fe5c78e8c の反映です。
=> docs: add manualChunks object form syntax warning when it is used with the splitVendorChunk plugin

guide/index.md
resolve: https://github.com/vitejs/docs-ja/issues/1029
https://github.com/vitejs/vite/commit/95f092ffb55e414ab7937d7aa1b68db91e4626fe の反映です。
=> docs: reference to qwik templates in getting starter guide

guide/static-deploy.md
resolves https://github.com/vitejs/docs-ja/issues/1041
https://github.com/vitejs/vite/commit/bf51ed4e8e40d902fa9e12569e100bca273d2119 の反映です。
=> docs(static-deploy): add deployment instructions for AWS Amplify Hosting

guide/features.md
resolves https://github.com/vitejs/docs-ja/issues/1042
https://github.com/vitejs/vite/commit/bbd1ffd2751b2e32eefa24958598c85026acf19a の反映です。
=> docs: remove note about firefox not supporting ESM imports in Web Workers

guide/cli.md, guide/troubleshooting.md
resolves: https://github.com/vitejs/docs-ja/issues/1048
resolves: https://github.com/vitejs/docs-ja/issues/1057
https://github.com/vitejs/vite/commit/77175099489ffbabefb9d98d448c782ced2986b5, https://github.com/vitejs/vite/commit/89fc7946c04f029bf9fdf09526daa569f4e38fc0 の反映です。
=> docs include profiler

.vitepress/theme/index.ts
resolves #1090
Cherry picked from https://github.com/vitejs/vite/commit/dc5896cf0b24b2313855a2bbd32e7bf9c33c5c69
=> docs: use extends instead of spreading default theme (#1090)

.vitepress/config.ts, guide/migration.md
https://github.com/vitejs/vite/blob/094f30fc54c9f07ab86bc46872b64b5397be573e/docs/guide/migration.md
この版を基に翻訳しました
resolve #1102
resolve #1114
resolve #1121
resolve #1122 
resolve #1123 
resolve #1128 
resolve #1129 
refs #1130 (ほかページの変更をしてません)
refs #1132 (ほかページの変更をしてません)
refs #1134 (ほかページの変更をしてません)
resolve #1139 
refs #1143 (ほかページの変更をしてません)
refs #1145 (ほかページの変更をしてません)
resolve #1146 
resolve #1147 
refs #1148 (ほかページの変更をしてません)
resolve #1150
resolve #1156 
refs #1157 (ほかページの変更をしてません)
resolve #1160
=> docs: docs: v4 to v5 migration guide

config/shared-options.md
resolve #1168
vitejs/vite@1e9bf06 の反映です
=> docs: clarify origin part of `base` is not used in dev

config/server-options.md
resolve #1267
https://github.com/vitejs/vite/commit/2836276dc0e132c4d64dc4c08fc730058406f2c0 の反映です。
=> fix(hmr): make watcher ignore build.outDir

guide/api-javascript.md
resolve #1303
https://github.com/vitejs/vite/commit/55a3427ef8ff491de913f304cb404551e33265bd の反映です。
行数がずれているので、#1306 のマージを先にお願いします。
=> fix: pass `customLogger` to `loadConfigFromFile` (fix #15824)

guide/api-hmr.md, guide/api-plugin.md
resolve #1339
https://github.com/vitejs/vite/commit/18b9b31d79d2a05e10b519a9f112fe857c1b7202 の反映です。
1行だけ過去のコミット (https://github.com/vitejs/vite/commit/1f57f84321c0d30daf8315e63d5a8f30c16635d1) が抜けている場所を見つけたので、こちらも同時に更新しました
=> docs(hmr): improve handleHotUpdate and add further reading

guide/assets.md
resolve #1343
https://github.com/vitejs/vite/commit/0c0aeaeb3f12d2cdc3c47557da209416c8d48fb7 の反映です。
=> docs(assets): add note to inlining SVG through url()

guide/backend-integration.md
resolve #1379
vitejs/vite@c2d0b88 の反映です
=> docs: use href attribute for link with rel=modulepreload

.vitepress/config.ts
resolves #1391
Cherry picked from https://github.com/vitejs/vite/commit/60367eee87e0764d7137320827f3975d6a45bd2c
=> docs: add Mastodon to “resources” in docs navigation (#1391)

config/build-options.md, guide/build.md, package.json, pnpm-lock.yaml
resolve #1420
https://github.com/vitejs/vite/commit/4501b5a7ea524d448e4da94988f4ed6d2d55dbe0 の反映です。
---
resolve #1413
https://github.com/vitejs/vite/commit/671155337af795156fe40a95935a8d2b27af1048
#1413 にも同じ `docs/package.json` の更新が1行あったので、こちらの変更も含めました。
=> chore(deps): update @shikijs/vitepress-twoslash to 1.5.0

.github/workflows/lint.yml
3つのActionsでそれぞれ新しいメジャーバージョンがリリースされていたので更新しました。
=> `lint.yml` で使われている Actions のバージョンを更新

guide/api-javascript.md
前回の翻訳 (https://github.com/vitejs/docs-ja/pull/1449) で「型シグネチャー」とすべきところを「型」と訳してしまっていたので、その修正です。
=> "Type signature" の翻訳ミスを修正

guide/build.md
resolve #1474 resolve #1475
vitejs/vite@a97e059, vitejs/vite@61357f6 の反映です
=> docs: switch Polyfill.io to Cloudflare hosted version

guide/api-plugin.md
resolve #1501
resolve #1505
https://github.com/vitejs/vite/commit/a7f98278a40e284b6ae638d42b3a34d95df7eb41 と https://github.com/vitejs/vite/commit/11b12cf284232b56991084327df32daaf603e488 の反映です。
=> docs: clarify when `transformIndexHtml` hook runs or not

config/shared-options.md, guide/features.md
resolve #1512
https://github.com/vitejs/vite/commit/1025bb6d8f21c0cb9fe72405d42e0f91bb3f1d8e の反映です。
=> feat(css): support sass compiler api and sass-embedded package

.vitepress/theme/components/AsideSponsors.vue
バナーが崩れていた。
このスタイル変更のコミット https://github.com/vitejs/vite/commit/be2829d0cca66ca008d25971258bdf755899167c は ryu-cho で連携されなかった模様
=> fix banner styles

.vitepress/config.ts, .vitepress/theme/index.ts, config/server-options.md, guide/api-javascript.md, guide/api-plugin.md, guide/backend-integration.md, guide/build.md, guide/dep-pre-bundling.md, guide/env-and-mode.md, guide/features.md, guide/index.md, guide/performance.md, guide/ssr.md, guide/static-deploy.md, guide/using-plugins.md, package.json, pnpm-lock.yaml
resolve #1550
https://github.com/vitejs/vite/commit/b529b6fa7d0c7707d0665e76cab78ae1f2422bcb の反映です。
=> docs: add `vitepress-plugin-group-icons`

guide/api-environment.md
resolve #1558
vitejs/vite@08ff233 の反映です
=> refactor: remove the need for "processSourceMap"

.vitepress/buildEnd.config.ts, .vitepress/config.ts, LICENSE
resolve #1579
https://github.com/vitejs/vite/commit/56eb869a67551a257d20cba00016ea59b1e1a2c4 の反映です。
=> chore: update license copyright

.vitepress/theme/styles/vars.css
resolves #1590
Cherry picked from https://github.com/vitejs/vite/commit/084194f96a6d2cb259b2055a6d7d6bcf23d3ba11
=> docs: make docsearch background darker (#1590)

guide/env-and-mode.md
resolve #1607
https://github.com/vitejs/vite/commit/e9c9767ba5bb1be89f695196e9a074667ecef7c9 の反映です。
=> docs: env expand feature only works for variables in env files

.vitepress/theme/components/AsideSponsors.vue, .vitepress/theme/components/landing/1. hero-section/HeroSection.vue
resolve #1606
https://github.com/vitejs/vite/commit/93b03b2692cc2617570f83e365606dae0a8ed859 の反映です。
=> docs: update ViteConf 24 cta

config/dep-optimization-options.md, config/server-options.md, guide/features.md
resolve #1615
https://github.com/vitejs/vite/commit/6f74a3a1b2469a24a86743d16267b0cc3653bc4a の反映です。
=> chore(deps)!: migrate `fast-glob` to `tinyglobby`

guide/why.md
resolve #1618
https://github.com/vitejs/vite/commit/164432121fae1d6e7b598648fb778d9540b5fa4e の反映です。
=> docs: mention pre-bundle uses esbuild in dev

guide/features.md
resolve #1623
https://github.com/vitejs/vite/commit/dcf5f03cb5c0a4a178fc7a97c43ac7c134749dcf の反映です。
=> docs: clarify `target` in `tsconfig.json`

config/server-options.md, guide/assets.md, guide/why.md
ref. #1624
MDNへのリンク3ヶ所、Microsoftの記事へのリンク1ヶ所を日本語版に変更します。
=> リンク先を日本語版のページに変更

guide/performance.md
resolve #1636
https://github.com/vitejs/vite/commit/ff018dca959c73481ae5f8328cd77d3b02f02134 の反映です。
=> chore: update moduleResolution value casing

config/build-options.md
resolve #1642
https://github.com/vitejs/vite/commit/19ce525b974328e4668ad8c6540c2a5ea652795b の反映です。
=> refactor!: bump minimal terser version to 5.16.0

guide/api-environment-frameworks.md, guide/cli.md
resolve #1644
vitejs/vite@cc61d16 の反映です
=> refactor: use builder in `build`

config/build-options.md
resolve #1648
vitejs/vite@f1d3bf7 の migration 以外の反映です
=> fix!: default `build.cssMinify` to `'esbuild'` for SSR

config/shared-options.md
resolve #1649
vitejs/vite@d23a493 の反映です
=> feat(css)!: load postcss config within workspace root only

config/shared-options.md
resolve #1652 
vitejs/vite@d4e0442 の反映です
=> feat(css)!: change default sass api to modern/modern-compiler

guide/troubleshooting.md
resolve #1666
https://github.com/vitejs/vite/commit/f886f75396cdb5a43ec5377bbbaaffc0e8ae03e9 の反映です。
=> fix(config): remove error if require resolve to esm

guide/features.md
resolve #1670
vitejs/vite@d951310 の反映です
=> feat(html): support `vite-ignore` attribute to opt-out of processing

config/build-options.md, guide/build.md, guide/migration.md
resolve #1671
vitejs/vite@61cbf6f の反映です
=> feat(lib)!: use package name for css output file name

changes/per-environment-apis.md, changes/shared-plugins-during-build.md
resolve #1673
vitejs/vite@5da78a6 の反映です
=> docs: missing changes guides

config/server-options.md, guide/migration.md
resolve #1675
vitejs/vite@94b0857 の反映です
=> refactor!: remove fs.cachedChecks option

guide/features.md, guide/migration.md
resolve #1676 resolve #1677
vitejs/vite@8a7af50, vitejs/vite@f65d6ae の反映です
=> feat(html)!: support more asset sources

.vitepress/config.ts, _data/team.js, package.json, pnpm-lock.yaml
=> docs: add bluesky profiles

config/index.md, config/server-options.md, guide/api-environment-frameworks.md, guide/api-environment-plugins.md, guide/api-environment-runtimes.md, guide/build.md
resolve #1692
vitejs/vite@a55e86b の反映です
=> docs: remove horizontal scrollbars in code blocks

config/shared-options.md, config/ssr-options.md, guide/migration.md
resolve #1678
https://github.com/vitejs/vite/commit/d002e7d05a0f23110f9185b39222819bcdfffc16 の反映です。
=> feat(resolve)!: allow removing conditions

guide/migration.md
resolve #1698 resolve #1699
vitejs/vite@61d0cfe, vitejs/vite@7523a9f の反映です
=> docs(migration): add bundle size note about strictRequires true

guide/assets.md
resolve #1704
https://github.com/vitejs/vite/commit/d969d4db91be2bece7d2094f5b4d573799297a49 の反映です。
=> docs: clarify dynamic `new URL(foo, import.meta.url)` behavior

changes/shared-plugins-during-build.md, guide/api-environment-plugins.md
resolve #1726
https://github.com/vitejs/vite/commit/8fa70cdfa65ce8254ab8da8be0d92614126764c0 の反映です。
=> feat: extended applyToEnvironment and perEnvironmentPlugin

config/server-options.md, guide/api-javascript.md
resolve #1729
vitejs/vite@49783da の反映です
=> revert: use chokidar v3

changes/hotupdate-hook.md, guide/api-environment-plugins.md
resolve #1736 
vitejs/vite@824c347 の反映です
=> docs: rename `HotUpdateContext` to `HotUpdateOptions`

guide/migration.md
resolve #1737
https://github.com/vitejs/vite/commit/0c658de41f4c1576c526a8c48a8ea0a019c6311c の反映です。
=> fix(deps)!: update dependency dotenv-expand to v12

changes/ssr-using-modulerunner.md
resolve #1744
vitejs/vite@4f60046 の反映です
=> docs: changes ssr using module runner

guide/migration.md, package.json, pnpm-lock.yaml
resolve #1743
vitejs/vite@ce50bd4 の反映です
=> docs(migration): note ssr-only module reload

guide/api-environment-runtimes.md
resolve #1742
https://github.com/vitejs/vite/commit/4d2abc7bba95cf516ce7341d5d8f349d61b75224 の反映です。
=> feat: enable HMR by default on ModuleRunner side

guide/api-environment-instances.md, guide/api-environment-runtimes.md, package.json, pnpm-lock.yaml
resolve #1745
vitejs/vite@db697ef の反映です
=> docs: add missing types in env API docs

package.json, pnpm-lock.yaml
resolve #1780
https://github.com/vitejs/vite/commit/ef7a6a35e6827b92445e5a0c2c0022616efc80dd の反映です。
=> chore(deps): update all non-major dependencies

config/server-options.md
resolve #1812
https://github.com/vitejs/vite/commit/3d038997377a30022b6a6b7916e0b4b5d8b9a363 の反映です
=> fix: allow CORS from loopback addresses by default

guide/build.md
resolve #1817 
https://github.com/vitejs/vite/commit/b7bd7b0f6918d71f49a9249f353a6a264111abb8 の反映です
=> docs: clarify browser compatibility

guide/troubleshooting.md
resolve #1828
https://github.com/vitejs/vite/commit/f19ffbcf3111df45206e95909592b2b75ec76e10 の反映です。
=> docs: add a trouble shooting section for DevContainers

guide/env-and-mode.md
resolve #1831 
https://github.com/vitejs/vite/commit/3f5f2bddf142b2d1b162d4553d26f1ff0758b10d の反映です
=> fix: allow expanding env vars in reverse order

guide/features.md
resolve #1850
https://github.com/vitejs/vite/commit/367cec1d89298c6d4591f84b2fb1bbbc33dd6b70 の反映です。
=> docs: add warning about overriding tsconfig types

guide/why.md
https://github.com/vitejs/docs-ja/pull/1858#issuecomment-2656867105 の追加修正です 🙏🏻 
https://deploy-preview-1860--vitejs-docs-ja.netlify.app/guide/comparisons でリダイレクトの動作が確認できます
=> リダイレクト先のアンカーリンクを修正

.vitepress/config.ts
resolve #1853
https://github.com/vitejs/vite/commit/3e07b178a334f241b9e6316a1dcf9e110778903a の反映です。
「Introduction」の訳に少し迷っています。原文は「Introduction」と「Getting started」で、今は両方とも「はじめに」と訳してみましたが、2つ同じ名前が並んでいると違和感があるような気もします。
他に「導入」や「イントロダクション」とも訳せると思いますが、どの訳が一番いいでしょうか？ 🤔
=> docs: extract introduction section

guide/features.md
resolve #1863
https://github.com/vitejs/vite/commit/335e2155c4d09f73e156667fd061b460224f8199 の反映です。
=> docs: framework agnostic features guide 

package.json, pnpm-lock.yaml
resolve #1879
https://github.com/vitejs/vite/commit/f4e712ff861f8a9504594a4a5e6d35a7547e5a7e の反映です。
=> fix(deps): update all non-major dependencies

config/preview-options.md, config/server-options.md
resolve #1883
https://github.com/vitejs/vite/commit/48151b3e3e522e1d9bb63bcb625a003cced41653 の反映です。
=> docs: `server.https` option is always an options object

.vitepress/theme/components/AsideSponsors.vue, .vitepress/theme/components/landing/1. hero-section/HeroSection.vue
resolve #1881
https://github.com/vitejs/vite/commit/cc2d623dca58ca3e006ecb1ffda89c16373bd20c の反映です。
`AsideSponsors`のバナーはこのような感じで表示されます。
=> docs: update to viteconf 2025

.vitepress/config.ts, guide/performance.md, guide/rolldown.md
resolve #1887
https://github.com/vitejs/vite/commit/3d2f42bc2f49f8cc20770f627e4f0395df63b297 の反映です
=> docs: add rolldown chapter

guide/api-environment-frameworks.md
resolve #1892
https://github.com/vitejs/vite/commit/c5b71915099cfbc15447a166f35620fa0e05c023 の反映です
=> feat(experimental): add fetchable environment interface

guide/features.md
resolve #1896
https://github.com/vitejs/vite/commit/66b2d91abcb2f0e36f1225ea51444823563b7a60 の反映です。
=> docs: remove lightningcss preprocessor note

changes/shared-plugins-during-build.md
resolve #1900
https://github.com/vitejs/vite/commit/eef06035a51701d2c25e3359ae308ea2ffb5dbbc の反映です。
=> docs: fix broken link to shared-plugins-during-build section

config/shared-options.md
resolve #1908
https://github.com/vitejs/vite/commit/93d639e13e17332f2d437dee3aeeab4d980c3eb5 の反映です。
=> docs: remove deprecated folder mapping exports warning

guide/static-deploy.md
resolve #1914 
https://github.com/vitejs/vite/commit/e051936db12b52b11e39ce15e87d634c14e50d14 の反映です
=> docs: bump node version to LTS

.textlintrc, guide/static-deploy-github-pages.yaml, guide/static-deploy.md
resolve #1921
https://github.com/vitejs/vite/commit/6ba4b8d087a7164da3950d19b0b7a1ee7ea2efd1 の反映です
=> docs(static-deploy): extract github workflow file for renovate

guide/index.md
resolve #1936
https://github.com/vitejs/vite/commit/6d0f01ea448444190a0d759ccf36383758ae254b の反映です
=> docs: add Deno commands

guide/api-hmr.md
resolve #1885
https://github.com/vitejs/vite/commit/95424b26892b005f438169d0ea426cb1a3176bf2 の反映です。
=> feat(types): type hints for hmr events

changes/this-environment-in-hooks.md
resolve #1948
https://github.com/vitejs/vite/commit/d4d8ade2b367860940ddc6816a24e9c6e62ad333 の反映です。
=> docs: update `options.ssr` migration guide

config/shared-options.md
resolve #1952 
https://github.com/vitejs/vite/commit/6eaccc9009d718a1afcff2af587e81eb959f5b60 の反映です
=> refactor(css)!: remove sass legacy API support

guide/features.md
resolve #1964
https://github.com/vitejs/vite/commit/7332e9e1fdc7d9f5b3b3201d70ad40cc520c9c78 の反映です。
=> docs: image svg element use href attribute

config/build-options.md, guide/build.md, guide/index.md
resolve #1967
https://github.com/vitejs/vite/commit/4a8aa82556eb2b9e54673a6aac77873e0eb27fa9 の反映です
=> feat!: bump `build.target` and name it `baseline-widely-available`

config/shared-options.md
resolve #1978 
https://github.com/vitejs/vite/commit/3bfe5c5ff96af0a0624c8f14503ef87a0c0850ed の反映です
=> refactor(css)!: always use sass compiler API

guide/rolldown.md
resolve #1986
https://github.com/vitejs/vite/commit/a72b3d9c4d1746ce786b37a48f93750c9c0b59bd の反映です
=> docs(rolldown): fix regex pattern in withFilter example for SVG imports

.vitepress/config.ts, guide/migration.md
resolve #2026
https://github.com/vitejs/vite/commit/b8a6abcf71549a223834f09a1a2d606988389d21 の反映です
=> docs: migration guide for v7

.vitepress/theme/components/SponsorBanner.vue, .vitepress/theme/components/landing/3. frameworks-section/FrameworkCard.vue, .vitepress/theme/components/landing/4. community-section/CommunityCard.vue, .vitepress/theme/components/landing/4. community-section/CommunitySection.vue, .vitepress/theme/components/landing/5. sponsor-section/SponsorSection.vue, guide/index.md
resolve #2076
https://github.com/vitejs/vite/commit/546588ab5ef77393b21eb2a6da363e4d2b32235d の反映です
=> docs: minor fixes

.vitepress/theme/styles/landing.css, index.md
resolve #2092
https://github.com/vitejs/vite/commit/557f797d29422027e8c451ca50dd84bf8c41b5f0 の反映です
=> docs: dark mode not applied properly in landing page

guide/rolldown.md
resolve #2106
https://github.com/vitejs/vite/commit/9ecc5f9eee1145f2f8b6216f3830ac29150caf28 の反映です
=> docs(rolldown): update `plugin-react-oxc` mention

config/index.md
resolve #2133
https://github.com/vitejs/vite/commit/d0ebe36b85cd4d83343e1c4aaf71bbf0dca3fd6f の反映です
=> docs(config): clarify environment variable loading in Vite config

guide/rolldown.md
resolve #2136
https://github.com/vitejs/vite/commit/9719497adec4ad5ead21cafa19a324bb1d480194 の反映です
=> docs(rolldown): update hook filter link

config/server-options.md
resolve #2142
https://github.com/vitejs/vite/commit/7f6af9d8717f840404a43e1de65436e87216936f の反映です
=> docs(server): add reference link for 'server.watcher' null behavior

guide/api-environment-plugins.md, guide/api-plugin.md
resolve #2145
https://github.com/vitejs/vite/commit/63244e89f299b81462f855a5fcc808c028158d43 の反映です
=> docs: clarify kind for `hotUpdate` / `handleHotUpdate` hooks
